// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package docker_test

import (
	"context"
	"io"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/events"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/api/types/network"
	"github.com/opencontainers/image-spec/specs-go/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerCreate provides a mock function for the type MockClient
func (_mock *MockClient) ContainerCreate(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, name string) (container.CreateResponse, error) {
	ret := _mock.Called(ctx, config, hostConfig, networkingConfig, platform, name)

	if len(ret) == 0 {
		panic("no return value specified for ContainerCreate")
	}

	var r0 container.CreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, *v1.Platform, string) (container.CreateResponse, error)); ok {
		return returnFunc(ctx, config, hostConfig, networkingConfig, platform, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, *v1.Platform, string) container.CreateResponse); ok {
		r0 = returnFunc(ctx, config, hostConfig, networkingConfig, platform, name)
	} else {
		r0 = ret.Get(0).(container.CreateResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, *v1.Platform, string) error); ok {
		r1 = returnFunc(ctx, config, hostConfig, networkingConfig, platform, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerCreate'
type MockClient_ContainerCreate_Call struct {
	*mock.Call
}

// ContainerCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - config *container.Config
//   - hostConfig *container.HostConfig
//   - networkingConfig *network.NetworkingConfig
//   - platform *v1.Platform
//   - name string
func (_e *MockClient_Expecter) ContainerCreate(ctx any, config any, hostConfig any, networkingConfig any, platform any, name any) *MockClient_ContainerCreate_Call {
	return &MockClient_ContainerCreate_Call{Call: _e.mock.On("ContainerCreate", ctx, config, hostConfig, networkingConfig, platform, name)}
}

func (_c *MockClient_ContainerCreate_Call) Run(run func(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, name string)) *MockClient_ContainerCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *container.Config
		if args[1] != nil {
			arg1 = args[1].(*container.Config)
		}
		var arg2 *container.HostConfig
		if args[2] != nil {
			arg2 = args[2].(*container.HostConfig)
		}
		var arg3 *network.NetworkingConfig
		if args[3] != nil {
			arg3 = args[3].(*network.NetworkingConfig)
		}
		var arg4 *v1.Platform
		if args[4] != nil {
			arg4 = args[4].(*v1.Platform)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_ContainerCreate_Call) Return(createResponse container.CreateResponse, err error) *MockClient_ContainerCreate_Call {
	_c.Call.Return(createResponse, err)
	return _c
}

func (_c *MockClient_ContainerCreate_Call) RunAndReturn(run func(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, name string) (container.CreateResponse, error)) *MockClient_ContainerCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerInspect provides a mock function for the type MockClient
func (_mock *MockClient) ContainerInspect(ctx context.Context, id string) (container.InspectResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ContainerInspect")
	}

	var r0 container.InspectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (container.InspectResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) container.InspectResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(container.InspectResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspect'
type MockClient_ContainerInspect_Call struct {
	*mock.Call
}

// ContainerInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClient_Expecter) ContainerInspect(ctx any, id any) *MockClient_ContainerInspect_Call {
	return &MockClient_ContainerInspect_Call{Call: _e.mock.On("ContainerInspect", ctx, id)}
}

func (_c *MockClient_ContainerInspect_Call) Run(run func(ctx context.Context, id string)) *MockClient_ContainerInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ContainerInspect_Call) Return(inspectResponse container.InspectResponse, err error) *MockClient_ContainerInspect_Call {
	_c.Call.Return(inspectResponse, err)
	return _c
}

func (_c *MockClient_ContainerInspect_Call) RunAndReturn(run func(ctx context.Context, id string) (container.InspectResponse, error)) *MockClient_ContainerInspect_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerList provides a mock function for the type MockClient
func (_mock *MockClient) ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerList")
	}

	var r0 []container.Summary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, container.ListOptions) ([]container.Summary, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, container.ListOptions) []container.Summary); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]container.Summary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, container.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerList'
type MockClient_ContainerList_Call struct {
	*mock.Call
}

// ContainerList is a helper method to define mock.On call
//   - ctx context.Context
//   - options container.ListOptions
func (_e *MockClient_Expecter) ContainerList(ctx any, options any) *MockClient_ContainerList_Call {
	return &MockClient_ContainerList_Call{Call: _e.mock.On("ContainerList", ctx, options)}
}

func (_c *MockClient_ContainerList_Call) Run(run func(ctx context.Context, options container.ListOptions)) *MockClient_ContainerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 container.ListOptions
		if args[1] != nil {
			arg1 = args[1].(container.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ContainerList_Call) Return(summarys []container.Summary, err error) *MockClient_ContainerList_Call {
	_c.Call.Return(summarys, err)
	return _c
}

func (_c *MockClient_ContainerList_Call) RunAndReturn(run func(ctx context.Context, options container.ListOptions) ([]container.Summary, error)) *MockClient_ContainerList_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerLogs provides a mock function for the type MockClient
func (_mock *MockClient) ContainerLogs(ctx context.Context, id string, options container.LogsOptions) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, id, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerLogs")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.LogsOptions) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, id, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.LogsOptions) io.ReadCloser); ok {
		r0 = returnFunc(ctx, id, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, container.LogsOptions) error); ok {
		r1 = returnFunc(ctx, id, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerLogs'
type MockClient_ContainerLogs_Call struct {
	*mock.Call
}

// ContainerLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - options container.LogsOptions
func (_e *MockClient_Expecter) ContainerLogs(ctx any, id any, options any) *MockClient_ContainerLogs_Call {
	return &MockClient_ContainerLogs_Call{Call: _e.mock.On("ContainerLogs", ctx, id, options)}
}

func (_c *MockClient_ContainerLogs_Call) Run(run func(ctx context.Context, id string, options container.LogsOptions)) *MockClient_ContainerLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.LogsOptions
		if args[2] != nil {
			arg2 = args[2].(container.LogsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerLogs_Call) Return(readCloser io.ReadCloser, err error) *MockClient_ContainerLogs_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockClient_ContainerLogs_Call) RunAndReturn(run func(ctx context.Context, id string, options container.LogsOptions) (io.ReadCloser, error)) *MockClient_ContainerLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerRemove provides a mock function for the type MockClient
func (_mock *MockClient) ContainerRemove(ctx context.Context, id string, options container.RemoveOptions) error {
	ret := _mock.Called(ctx, id, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRemove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.RemoveOptions) error); ok {
		r0 = returnFunc(ctx, id, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ContainerRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRemove'
type MockClient_ContainerRemove_Call struct {
	*mock.Call
}

// ContainerRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - options container.RemoveOptions
func (_e *MockClient_Expecter) ContainerRemove(ctx any, id any, options any) *MockClient_ContainerRemove_Call {
	return &MockClient_ContainerRemove_Call{Call: _e.mock.On("ContainerRemove", ctx, id, options)}
}

func (_c *MockClient_ContainerRemove_Call) Run(run func(ctx context.Context, id string, options container.RemoveOptions)) *MockClient_ContainerRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.RemoveOptions
		if args[2] != nil {
			arg2 = args[2].(container.RemoveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerRemove_Call) Return(err error) *MockClient_ContainerRemove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ContainerRemove_Call) RunAndReturn(run func(ctx context.Context, id string, options container.RemoveOptions) error) *MockClient_ContainerRemove_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStart provides a mock function for the type MockClient
func (_mock *MockClient) ContainerStart(ctx context.Context, id string, options container.StartOptions) error {
	ret := _mock.Called(ctx, id, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.StartOptions) error); ok {
		r0 = returnFunc(ctx, id, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ContainerStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStart'
type MockClient_ContainerStart_Call struct {
	*mock.Call
}

// ContainerStart is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - options container.StartOptions
func (_e *MockClient_Expecter) ContainerStart(ctx any, id any, options any) *MockClient_ContainerStart_Call {
	return &MockClient_ContainerStart_Call{Call: _e.mock.On("ContainerStart", ctx, id, options)}
}

func (_c *MockClient_ContainerStart_Call) Run(run func(ctx context.Context, id string, options container.StartOptions)) *MockClient_ContainerStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.StartOptions
		if args[2] != nil {
			arg2 = args[2].(container.StartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerStart_Call) Return(err error) *MockClient_ContainerStart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ContainerStart_Call) RunAndReturn(run func(ctx context.Context, id string, options container.StartOptions) error) *MockClient_ContainerStart_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStop provides a mock function for the type MockClient
func (_mock *MockClient) ContainerStop(ctx context.Context, id string, options container.StopOptions) error {
	ret := _mock.Called(ctx, id, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.StopOptions) error); ok {
		r0 = returnFunc(ctx, id, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ContainerStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStop'
type MockClient_ContainerStop_Call struct {
	*mock.Call
}

// ContainerStop is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - options container.StopOptions
func (_e *MockClient_Expecter) ContainerStop(ctx any, id any, options any) *MockClient_ContainerStop_Call {
	return &MockClient_ContainerStop_Call{Call: _e.mock.On("ContainerStop", ctx, id, options)}
}

func (_c *MockClient_ContainerStop_Call) Run(run func(ctx context.Context, id string, options container.StopOptions)) *MockClient_ContainerStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.StopOptions
		if args[2] != nil {
			arg2 = args[2].(container.StopOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerStop_Call) Return(err error) *MockClient_ContainerStop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ContainerStop_Call) RunAndReturn(run func(ctx context.Context, id string, options container.StopOptions) error) *MockClient_ContainerStop_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function for the type MockClient
func (_mock *MockClient) Events(ctx context.Context, options events.ListOptions) (<-chan events.Message, <-chan error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 <-chan events.Message
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, events.ListOptions) (<-chan events.Message, <-chan error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, events.ListOptions) <-chan events.Message); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan events.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, events.ListOptions) <-chan error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// MockClient_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type MockClient_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - ctx context.Context
//   - options events.ListOptions
func (_e *MockClient_Expecter) Events(ctx any, options any) *MockClient_Events_Call {
	return &MockClient_Events_Call{Call: _e.mock.On("Events", ctx, options)}
}

func (_c *MockClient_Events_Call) Run(run func(ctx context.Context, options events.ListOptions)) *MockClient_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 events.ListOptions
		if args[1] != nil {
			arg1 = args[1].(events.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Events_Call) Return(messageCh <-chan events.Message, errCh <-chan error) *MockClient_Events_Call {
	_c.Call.Return(messageCh, errCh)
	return _c
}

func (_c *MockClient_Events_Call) RunAndReturn(run func(ctx context.Context, options events.ListOptions) (<-chan events.Message, <-chan error)) *MockClient_Events_Call {
	_c.Call.Return(run)
	return _c
}

// ImageList provides a mock function for the type MockClient
func (_mock *MockClient) ImageList(ctx context.Context, options image.ListOptions) ([]image.Summary, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ImageList")
	}

	var r0 []image.Summary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.ListOptions) ([]image.Summary, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.ListOptions) []image.Summary); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]image.Summary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, image.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImageList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageList'
type MockClient_ImageList_Call struct {
	*mock.Call
}

// ImageList is a helper method to define mock.On call
//   - ctx context.Context
//   - options image.ListOptions
func (_e *MockClient_Expecter) ImageList(ctx any, options any) *MockClient_ImageList_Call {
	return &MockClient_ImageList_Call{Call: _e.mock.On("ImageList", ctx, options)}
}

func (_c *MockClient_ImageList_Call) Run(run func(ctx context.Context, options image.ListOptions)) *MockClient_ImageList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 image.ListOptions
		if args[1] != nil {
			arg1 = args[1].(image.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ImageList_Call) Return(summarys []image.Summary, err error) *MockClient_ImageList_Call {
	_c.Call.Return(summarys, err)
	return _c
}

func (_c *MockClient_ImageList_Call) RunAndReturn(run func(ctx context.Context, options image.ListOptions) ([]image.Summary, error)) *MockClient_ImageList_Call {
	_c.Call.Return(run)
	return _c
}

// ImagePull provides a mock function for the type MockClient
func (_mock *MockClient) ImagePull(ctx context.Context, ref string, options image.PullOptions) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, ref, options)

	if len(ret) == 0 {
		panic("no return value specified for ImagePull")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, image.PullOptions) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, ref, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, image.PullOptions) io.ReadCloser); ok {
		r0 = returnFunc(ctx, ref, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, image.PullOptions) error); ok {
		r1 = returnFunc(ctx, ref, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImagePull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImagePull'
type MockClient_ImagePull_Call struct {
	*mock.Call
}

// ImagePull is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - options image.PullOptions
func (_e *MockClient_Expecter) ImagePull(ctx any, ref any, options any) *MockClient_ImagePull_Call {
	return &MockClient_ImagePull_Call{Call: _e.mock.On("ImagePull", ctx, ref, options)}
}

func (_c *MockClient_ImagePull_Call) Run(run func(ctx context.Context, ref string, options image.PullOptions)) *MockClient_ImagePull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 image.PullOptions
		if args[2] != nil {
			arg2 = args[2].(image.PullOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ImagePull_Call) Return(readCloser io.ReadCloser, err error) *MockClient_ImagePull_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockClient_ImagePull_Call) RunAndReturn(run func(ctx context.Context, ref string, options image.PullOptions) (io.ReadCloser, error)) *MockClient_ImagePull_Call {
	_c.Call.Return(run)
	return _c
}
