// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"context"

	"github.com/dsb-labs/orca/internal/server/database"
	"github.com/dsb-labs/orca/internal/server/driver"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// Logs provides a mock function for the type MockDriver
func (_mock *MockDriver) Logs(ctx context.Context, workload string, tail int) (string, error) {
	ret := _mock.Called(ctx, workload, tail)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (string, error)); ok {
		return returnFunc(ctx, workload, tail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) string); ok {
		r0 = returnFunc(ctx, workload, tail)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, workload, tail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type MockDriver_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - workload string
//   - tail int
func (_e *MockDriver_Expecter) Logs(ctx any, workload any, tail any) *MockDriver_Logs_Call {
	return &MockDriver_Logs_Call{Call: _e.mock.On("Logs", ctx, workload, tail)}
}

func (_c *MockDriver_Logs_Call) Run(run func(ctx context.Context, workload string, tail int)) *MockDriver_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Logs_Call) Return(s string, err error) *MockDriver_Logs_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDriver_Logs_Call) RunAndReturn(run func(ctx context.Context, workload string, tail int) (string, error)) *MockDriver_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Observe provides a mock function for the type MockDriver
func (_mock *MockDriver) Observe(ctx context.Context) ([]driver.Instance, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 []driver.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]driver.Instance, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []driver.Instance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]driver.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockDriver_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDriver_Expecter) Observe(ctx any) *MockDriver_Observe_Call {
	return &MockDriver_Observe_Call{Call: _e.mock.On("Observe", ctx)}
}

func (_c *MockDriver_Observe_Call) Run(run func(ctx context.Context)) *MockDriver_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Observe_Call) Return(instances []driver.Instance, err error) *MockDriver_Observe_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *MockDriver_Observe_Call) RunAndReturn(run func(ctx context.Context) ([]driver.Instance, error)) *MockDriver_Observe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkloadRepository creates a new instance of MockWorkloadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkloadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkloadRepository {
	mock := &MockWorkloadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkloadRepository is an autogenerated mock type for the WorkloadRepository type
type MockWorkloadRepository struct {
	mock.Mock
}

type MockWorkloadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkloadRepository) EXPECT() *MockWorkloadRepository_Expecter {
	return &MockWorkloadRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) Get(ctx context.Context, name string) (database.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 database.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(database.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkloadRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadRepository_Expecter) Get(ctx any, name any) *MockWorkloadRepository_Get_Call {
	return &MockWorkloadRepository_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockWorkloadRepository_Get_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_Get_Call) Return(workload database.Workload, err error) *MockWorkloadRepository_Get_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadRepository_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (database.Workload, error)) *MockWorkloadRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) List(ctx context.Context) ([]database.Workload, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]database.Workload, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []database.Workload); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkloadRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWorkloadRepository_Expecter) List(ctx any) *MockWorkloadRepository_List_Call {
	return &MockWorkloadRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockWorkloadRepository_List_Call) Run(run func(ctx context.Context)) *MockWorkloadRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_List_Call) Return(workloads []database.Workload, err error) *MockWorkloadRepository_List_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *MockWorkloadRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]database.Workload, error)) *MockWorkloadRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDeleting provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) MarkDeleting(ctx context.Context, name string) (database.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for MarkDeleting")
	}

	var r0 database.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(database.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadRepository_MarkDeleting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDeleting'
type MockWorkloadRepository_MarkDeleting_Call struct {
	*mock.Call
}

// MarkDeleting is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadRepository_Expecter) MarkDeleting(ctx any, name any) *MockWorkloadRepository_MarkDeleting_Call {
	return &MockWorkloadRepository_MarkDeleting_Call{Call: _e.mock.On("MarkDeleting", ctx, name)}
}

func (_c *MockWorkloadRepository_MarkDeleting_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadRepository_MarkDeleting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_MarkDeleting_Call) Return(workload database.Workload, err error) *MockWorkloadRepository_MarkDeleting_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadRepository_MarkDeleting_Call) RunAndReturn(run func(ctx context.Context, name string) (database.Workload, error)) *MockWorkloadRepository_MarkDeleting_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) Upsert(ctx context.Context, w database.Workload) (database.Workload, bool, error) {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 database.Workload
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.Workload) (database.Workload, bool, error)); ok {
		return returnFunc(ctx, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.Workload) database.Workload); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Get(0).(database.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.Workload) bool); ok {
		r1 = returnFunc(ctx, w)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, database.Workload) error); ok {
		r2 = returnFunc(ctx, w)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWorkloadRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockWorkloadRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - w database.Workload
func (_e *MockWorkloadRepository_Expecter) Upsert(ctx any, w any) *MockWorkloadRepository_Upsert_Call {
	return &MockWorkloadRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, w)}
}

func (_c *MockWorkloadRepository_Upsert_Call) Run(run func(ctx context.Context, w database.Workload)) *MockWorkloadRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.Workload
		if args[1] != nil {
			arg1 = args[1].(database.Workload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_Upsert_Call) Return(workload database.Workload, b bool, err error) *MockWorkloadRepository_Upsert_Call {
	_c.Call.Return(workload, b, err)
	return _c
}

func (_c *MockWorkloadRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, w database.Workload) (database.Workload, bool, error)) *MockWorkloadRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
