// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"context"

	"github.com/dsb-labs/orca/internal/server/database"
	"github.com/dsb-labs/orca/internal/server/driver"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// Logs provides a mock function for the type MockDriver
func (_mock *MockDriver) Logs(ctx context.Context, workload string, tail int) (string, error) {
	ret := _mock.Called(ctx, workload, tail)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (string, error)); ok {
		return returnFunc(ctx, workload, tail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) string); ok {
		r0 = returnFunc(ctx, workload, tail)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, workload, tail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type MockDriver_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - workload string
//   - tail int
func (_e *MockDriver_Expecter) Logs(ctx any, workload any, tail any) *MockDriver_Logs_Call {
	return &MockDriver_Logs_Call{Call: _e.mock.On("Logs", ctx, workload, tail)}
}

func (_c *MockDriver_Logs_Call) Run(run func(ctx context.Context, workload string, tail int)) *MockDriver_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Logs_Call) Return(s string, err error) *MockDriver_Logs_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDriver_Logs_Call) RunAndReturn(run func(ctx context.Context, workload string, tail int) (string, error)) *MockDriver_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Observe provides a mock function for the type MockDriver
func (_mock *MockDriver) Observe(ctx context.Context) ([]driver.Instance, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 []driver.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]driver.Instance, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []driver.Instance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]driver.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockDriver_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDriver_Expecter) Observe(ctx any) *MockDriver_Observe_Call {
	return &MockDriver_Observe_Call{Call: _e.mock.On("Observe", ctx)}
}

func (_c *MockDriver_Observe_Call) Run(run func(ctx context.Context)) *MockDriver_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Observe_Call) Return(instances []driver.Instance, err error) *MockDriver_Observe_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *MockDriver_Observe_Call) RunAndReturn(run func(ctx context.Context) ([]driver.Instance, error)) *MockDriver_Observe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkloadRepository creates a new instance of MockWorkloadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkloadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkloadRepository {
	mock := &MockWorkloadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkloadRepository is an autogenerated mock type for the WorkloadRepository type
type MockWorkloadRepository struct {
	mock.Mock
}

type MockWorkloadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkloadRepository) EXPECT() *MockWorkloadRepository_Expecter {
	return &MockWorkloadRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) Get(ctx context.Context, name string) (database.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 database.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(database.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkloadRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadRepository_Expecter) Get(ctx any, name any) *MockWorkloadRepository_Get_Call {
	return &MockWorkloadRepository_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockWorkloadRepository_Get_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_Get_Call) Return(workload database.Workload, err error) *MockWorkloadRepository_Get_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadRepository_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (database.Workload, error)) *MockWorkloadRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) List(ctx context.Context) ([]database.Workload, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]database.Workload, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []database.Workload); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkloadRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWorkloadRepository_Expecter) List(ctx any) *MockWorkloadRepository_List_Call {
	return &MockWorkloadRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockWorkloadRepository_List_Call) Run(run func(ctx context.Context)) *MockWorkloadRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_List_Call) Return(workloads []database.Workload, err error) *MockWorkloadRepository_List_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *MockWorkloadRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]database.Workload, error)) *MockWorkloadRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDeleting provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) MarkDeleting(ctx context.Context, name string) (database.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for MarkDeleting")
	}

	var r0 database.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(database.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadRepository_MarkDeleting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDeleting'
type MockWorkloadRepository_MarkDeleting_Call struct {
	*mock.Call
}

// MarkDeleting is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadRepository_Expecter) MarkDeleting(ctx any, name any) *MockWorkloadRepository_MarkDeleting_Call {
	return &MockWorkloadRepository_MarkDeleting_Call{Call: _e.mock.On("MarkDeleting", ctx, name)}
}

func (_c *MockWorkloadRepository_MarkDeleting_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadRepository_MarkDeleting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_MarkDeleting_Call) Return(workload database.Workload, err error) *MockWorkloadRepository_MarkDeleting_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadRepository_MarkDeleting_Call) RunAndReturn(run func(ctx context.Context, name string) (database.Workload, error)) *MockWorkloadRepository_MarkDeleting_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) Upsert(ctx context.Context, w database.Workload) (database.Workload, bool, error) {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 database.Workload
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.Workload) (database.Workload, bool, error)); ok {
		return returnFunc(ctx, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.Workload) database.Workload); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Get(0).(database.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.Workload) bool); ok {
		r1 = returnFunc(ctx, w)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, database.Workload) error); ok {
		r2 = returnFunc(ctx, w)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWorkloadRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockWorkloadRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - w database.Workload
func (_e *MockWorkloadRepository_Expecter) Upsert(ctx any, w any) *MockWorkloadRepository_Upsert_Call {
	return &MockWorkloadRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, w)}
}

func (_c *MockWorkloadRepository_Upsert_Call) Run(run func(ctx context.Context, w database.Workload)) *MockWorkloadRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.Workload
		if args[1] != nil {
			arg1 = args[1].(database.Workload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_Upsert_Call) Return(workload database.Workload, b bool, err error) *MockWorkloadRepository_Upsert_Call {
	_c.Call.Return(workload, b, err)
	return _c
}

func (_c *MockWorkloadRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, w database.Workload) (database.Workload, bool, error)) *MockWorkloadRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPortRepository creates a new instance of MockPortRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPortRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPortRepository {
	mock := &MockPortRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPortRepository is an autogenerated mock type for the PortRepository type
type MockPortRepository struct {
	mock.Mock
}

type MockPortRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPortRepository) EXPECT() *MockPortRepository_Expecter {
	return &MockPortRepository_Expecter{mock: &_m.Mock}
}

// Allocated provides a mock function for the type MockPortRepository
func (_mock *MockPortRepository) Allocated(ctx context.Context) ([]int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Allocated")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortRepository_Allocated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allocated'
type MockPortRepository_Allocated_Call struct {
	*mock.Call
}

// Allocated is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPortRepository_Expecter) Allocated(ctx any) *MockPortRepository_Allocated_Call {
	return &MockPortRepository_Allocated_Call{Call: _e.mock.On("Allocated", ctx)}
}

func (_c *MockPortRepository_Allocated_Call) Run(run func(ctx context.Context)) *MockPortRepository_Allocated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPortRepository_Allocated_Call) Return(ints []int, err error) *MockPortRepository_Allocated_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockPortRepository_Allocated_Call) RunAndReturn(run func(ctx context.Context) ([]int, error)) *MockPortRepository_Allocated_Call {
	_c.Call.Return(run)
	return _c
}

// Claim provides a mock function for the type MockPortRepository
func (_mock *MockPortRepository) Claim(ctx context.Context, workloadID string, ports []database.Port) error {
	ret := _mock.Called(ctx, workloadID, ports)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []database.Port) error); ok {
		r0 = returnFunc(ctx, workloadID, ports)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPortRepository_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockPortRepository_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - workloadID string
//   - ports []database.Port
func (_e *MockPortRepository_Expecter) Claim(ctx any, workloadID any, ports any) *MockPortRepository_Claim_Call {
	return &MockPortRepository_Claim_Call{Call: _e.mock.On("Claim", ctx, workloadID, ports)}
}

func (_c *MockPortRepository_Claim_Call) Run(run func(ctx context.Context, workloadID string, ports []database.Port)) *MockPortRepository_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []database.Port
		if args[2] != nil {
			arg2 = args[2].([]database.Port)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPortRepository_Claim_Call) Return(err error) *MockPortRepository_Claim_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPortRepository_Claim_Call) RunAndReturn(run func(ctx context.Context, workloadID string, ports []database.Port) error) *MockPortRepository_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// HolderOf provides a mock function for the type MockPortRepository
func (_mock *MockPortRepository) HolderOf(ctx context.Context, host int) (string, bool, error) {
	ret := _mock.Called(ctx, host)

	if len(ret) == 0 {
		panic("no return value specified for HolderOf")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, bool, error)); ok {
		return returnFunc(ctx, host)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, host)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = returnFunc(ctx, host)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, host)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPortRepository_HolderOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HolderOf'
type MockPortRepository_HolderOf_Call struct {
	*mock.Call
}

// HolderOf is a helper method to define mock.On call
//   - ctx context.Context
//   - host int
func (_e *MockPortRepository_Expecter) HolderOf(ctx any, host any) *MockPortRepository_HolderOf_Call {
	return &MockPortRepository_HolderOf_Call{Call: _e.mock.On("HolderOf", ctx, host)}
}

func (_c *MockPortRepository_HolderOf_Call) Run(run func(ctx context.Context, host int)) *MockPortRepository_HolderOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPortRepository_HolderOf_Call) Return(s string, b bool, err error) *MockPortRepository_HolderOf_Call {
	_c.Call.Return(s, b, err)
	return _c
}

func (_c *MockPortRepository_HolderOf_Call) RunAndReturn(run func(ctx context.Context, host int) (string, bool, error)) *MockPortRepository_HolderOf_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPortRepository
func (_mock *MockPortRepository) List(ctx context.Context, workloadID string) ([]database.Port, error) {
	ret := _mock.Called(ctx, workloadID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Port
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]database.Port, error)); ok {
		return returnFunc(ctx, workloadID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []database.Port); ok {
		r0 = returnFunc(ctx, workloadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Port)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workloadID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPortRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - workloadID string
func (_e *MockPortRepository_Expecter) List(ctx any, workloadID any) *MockPortRepository_List_Call {
	return &MockPortRepository_List_Call{Call: _e.mock.On("List", ctx, workloadID)}
}

func (_c *MockPortRepository_List_Call) Run(run func(ctx context.Context, workloadID string)) *MockPortRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPortRepository_List_Call) Return(ports []database.Port, err error) *MockPortRepository_List_Call {
	_c.Call.Return(ports, err)
	return _c
}

func (_c *MockPortRepository_List_Call) RunAndReturn(run func(ctx context.Context, workloadID string) ([]database.Port, error)) *MockPortRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAllocator creates a new instance of MockAllocator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAllocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAllocator {
	mock := &MockAllocator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAllocator is an autogenerated mock type for the Allocator type
type MockAllocator struct {
	mock.Mock
}

type MockAllocator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAllocator) EXPECT() *MockAllocator_Expecter {
	return &MockAllocator_Expecter{mock: &_m.Mock}
}

// Allocate provides a mock function for the type MockAllocator
func (_mock *MockAllocator) Allocate(taken []int) (int, error) {
	ret := _mock.Called(taken)

	if len(ret) == 0 {
		panic("no return value specified for Allocate")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int) (int, error)); ok {
		return returnFunc(taken)
	}
	if returnFunc, ok := ret.Get(0).(func([]int) int); ok {
		r0 = returnFunc(taken)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]int) error); ok {
		r1 = returnFunc(taken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAllocator_Allocate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allocate'
type MockAllocator_Allocate_Call struct {
	*mock.Call
}

// Allocate is a helper method to define mock.On call
//   - taken []int
func (_e *MockAllocator_Expecter) Allocate(taken any) *MockAllocator_Allocate_Call {
	return &MockAllocator_Allocate_Call{Call: _e.mock.On("Allocate", taken)}
}

func (_c *MockAllocator_Allocate_Call) Run(run func(taken []int)) *MockAllocator_Allocate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int
		if args[0] != nil {
			arg0 = args[0].([]int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAllocator_Allocate_Call) Return(n int, err error) *MockAllocator_Allocate_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAllocator_Allocate_Call) RunAndReturn(run func(taken []int) (int, error)) *MockAllocator_Allocate_Call {
	_c.Call.Return(run)
	return _c
}
