// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mount_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockValueStore creates a new instance of MockValueStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValueStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValueStore {
	mock := &MockValueStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValueStore is an autogenerated mock type for the ValueStore type
type MockValueStore struct {
	mock.Mock
}

type MockValueStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValueStore) EXPECT() *MockValueStore_Expecter {
	return &MockValueStore_Expecter{mock: &_m.Mock}
}

// Value provides a mock function for the type MockValueStore
func (_mock *MockValueStore) Value(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockValueStore_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type MockValueStore_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockValueStore_Expecter) Value(ctx any, name any) *MockValueStore_Value_Call {
	return &MockValueStore_Value_Call{Call: _e.mock.On("Value", ctx, name)}
}

func (_c *MockValueStore_Value_Call) Run(run func(ctx context.Context, name string)) *MockValueStore_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockValueStore_Value_Call) Return(s string, err error) *MockValueStore_Value_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockValueStore_Value_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockValueStore_Value_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokens creates a new instance of MockTokens. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokens(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokens {
	mock := &MockTokens{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokens is an autogenerated mock type for the Tokens type
type MockTokens struct {
	mock.Mock
}

type MockTokens_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokens) EXPECT() *MockTokens_Expecter {
	return &MockTokens_Expecter{mock: &_m.Mock}
}

// MintWorkloadToken provides a mock function for the type MockTokens
func (_mock *MockTokens) MintWorkloadToken(ctx context.Context, principal string, workloadID string, version int, expires bool) (string, error) {
	ret := _mock.Called(ctx, principal, workloadID, version, expires)

	if len(ret) == 0 {
		panic("no return value specified for MintWorkloadToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, bool) (string, error)); ok {
		return returnFunc(ctx, principal, workloadID, version, expires)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, bool) string); ok {
		r0 = returnFunc(ctx, principal, workloadID, version, expires)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, bool) error); ok {
		r1 = returnFunc(ctx, principal, workloadID, version, expires)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokens_MintWorkloadToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MintWorkloadToken'
type MockTokens_MintWorkloadToken_Call struct {
	*mock.Call
}

// MintWorkloadToken is a helper method to define mock.On call
//   - ctx context.Context
//   - principal string
//   - workloadID string
//   - version int
//   - expires bool
func (_e *MockTokens_Expecter) MintWorkloadToken(ctx any, principal any, workloadID any, version any, expires any) *MockTokens_MintWorkloadToken_Call {
	return &MockTokens_MintWorkloadToken_Call{Call: _e.mock.On("MintWorkloadToken", ctx, principal, workloadID, version, expires)}
}

func (_c *MockTokens_MintWorkloadToken_Call) Run(run func(ctx context.Context, principal string, workloadID string, version int, expires bool)) *MockTokens_MintWorkloadToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTokens_MintWorkloadToken_Call) Return(s string, err error) *MockTokens_MintWorkloadToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokens_MintWorkloadToken_Call) RunAndReturn(run func(ctx context.Context, principal string, workloadID string, version int, expires bool) (string, error)) *MockTokens_MintWorkloadToken_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshWorkloadToken provides a mock function for the type MockTokens
func (_mock *MockTokens) RefreshWorkloadToken(ctx context.Context, principal string, workloadID string, version int, expires bool) (string, bool, error) {
	ret := _mock.Called(ctx, principal, workloadID, version, expires)

	if len(ret) == 0 {
		panic("no return value specified for RefreshWorkloadToken")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, bool) (string, bool, error)); ok {
		return returnFunc(ctx, principal, workloadID, version, expires)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, bool) string); ok {
		r0 = returnFunc(ctx, principal, workloadID, version, expires)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, bool) bool); ok {
		r1 = returnFunc(ctx, principal, workloadID, version, expires)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, int, bool) error); ok {
		r2 = returnFunc(ctx, principal, workloadID, version, expires)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokens_RefreshWorkloadToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshWorkloadToken'
type MockTokens_RefreshWorkloadToken_Call struct {
	*mock.Call
}

// RefreshWorkloadToken is a helper method to define mock.On call
//   - ctx context.Context
//   - principal string
//   - workloadID string
//   - version int
//   - expires bool
func (_e *MockTokens_Expecter) RefreshWorkloadToken(ctx any, principal any, workloadID any, version any, expires any) *MockTokens_RefreshWorkloadToken_Call {
	return &MockTokens_RefreshWorkloadToken_Call{Call: _e.mock.On("RefreshWorkloadToken", ctx, principal, workloadID, version, expires)}
}

func (_c *MockTokens_RefreshWorkloadToken_Call) Run(run func(ctx context.Context, principal string, workloadID string, version int, expires bool)) *MockTokens_RefreshWorkloadToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTokens_RefreshWorkloadToken_Call) Return(s string, b bool, err error) *MockTokens_RefreshWorkloadToken_Call {
	_c.Call.Return(s, b, err)
	return _c
}

func (_c *MockTokens_RefreshWorkloadToken_Call) RunAndReturn(run func(ctx context.Context, principal string, workloadID string, version int, expires bool) (string, bool, error)) *MockTokens_RefreshWorkloadToken_Call {
	_c.Call.Return(run)
	return _c
}
