// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mount_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockValueStore creates a new instance of MockValueStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValueStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValueStore {
	mock := &MockValueStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValueStore is an autogenerated mock type for the ValueStore type
type MockValueStore struct {
	mock.Mock
}

type MockValueStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValueStore) EXPECT() *MockValueStore_Expecter {
	return &MockValueStore_Expecter{mock: &_m.Mock}
}

// Value provides a mock function for the type MockValueStore
func (_mock *MockValueStore) Value(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockValueStore_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type MockValueStore_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockValueStore_Expecter) Value(ctx any, name any) *MockValueStore_Value_Call {
	return &MockValueStore_Value_Call{Call: _e.mock.On("Value", ctx, name)}
}

func (_c *MockValueStore_Value_Call) Run(run func(ctx context.Context, name string)) *MockValueStore_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockValueStore_Value_Call) Return(s string, err error) *MockValueStore_Value_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockValueStore_Value_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockValueStore_Value_Call {
	_c.Call.Return(run)
	return _c
}
