// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resolve_test

import (
	"context"

	"github.com/dsb-labs/takt/internal/server/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkloadLocator creates a new instance of MockWorkloadLocator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkloadLocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkloadLocator {
	mock := &MockWorkloadLocator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkloadLocator is an autogenerated mock type for the WorkloadLocator type
type MockWorkloadLocator struct {
	mock.Mock
}

type MockWorkloadLocator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkloadLocator) EXPECT() *MockWorkloadLocator_Expecter {
	return &MockWorkloadLocator_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockWorkloadLocator
func (_mock *MockWorkloadLocator) Get(ctx context.Context, name string) (database.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 database.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(database.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadLocator_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkloadLocator_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadLocator_Expecter) Get(ctx any, name any) *MockWorkloadLocator_Get_Call {
	return &MockWorkloadLocator_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockWorkloadLocator_Get_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadLocator_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadLocator_Get_Call) Return(workload database.Workload, err error) *MockWorkloadLocator_Get_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadLocator_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (database.Workload, error)) *MockWorkloadLocator_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPortLocator creates a new instance of MockPortLocator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPortLocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPortLocator {
	mock := &MockPortLocator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPortLocator is an autogenerated mock type for the PortLocator type
type MockPortLocator struct {
	mock.Mock
}

type MockPortLocator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPortLocator) EXPECT() *MockPortLocator_Expecter {
	return &MockPortLocator_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockPortLocator
func (_mock *MockPortLocator) List(ctx context.Context, workloadID string) ([]database.Port, error) {
	ret := _mock.Called(ctx, workloadID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Port
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]database.Port, error)); ok {
		return returnFunc(ctx, workloadID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []database.Port); ok {
		r0 = returnFunc(ctx, workloadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Port)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workloadID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortLocator_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPortLocator_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - workloadID string
func (_e *MockPortLocator_Expecter) List(ctx any, workloadID any) *MockPortLocator_List_Call {
	return &MockPortLocator_List_Call{Call: _e.mock.On("List", ctx, workloadID)}
}

func (_c *MockPortLocator_List_Call) Run(run func(ctx context.Context, workloadID string)) *MockPortLocator_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPortLocator_List_Call) Return(ports []database.Port, err error) *MockPortLocator_List_Call {
	_c.Call.Return(ports, err)
	return _c
}

func (_c *MockPortLocator_List_Call) RunAndReturn(run func(ctx context.Context, workloadID string) ([]database.Port, error)) *MockPortLocator_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValueStore creates a new instance of MockValueStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValueStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValueStore {
	mock := &MockValueStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValueStore is an autogenerated mock type for the ValueStore type
type MockValueStore struct {
	mock.Mock
}

type MockValueStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValueStore) EXPECT() *MockValueStore_Expecter {
	return &MockValueStore_Expecter{mock: &_m.Mock}
}

// Value provides a mock function for the type MockValueStore
func (_mock *MockValueStore) Value(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockValueStore_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type MockValueStore_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockValueStore_Expecter) Value(ctx any, name any) *MockValueStore_Value_Call {
	return &MockValueStore_Value_Call{Call: _e.mock.On("Value", ctx, name)}
}

func (_c *MockValueStore_Value_Call) Run(run func(ctx context.Context, name string)) *MockValueStore_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockValueStore_Value_Call) Return(s string, err error) *MockValueStore_Value_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockValueStore_Value_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockValueStore_Value_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenMinter creates a new instance of MockTokenMinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenMinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenMinter {
	mock := &MockTokenMinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenMinter is an autogenerated mock type for the TokenMinter type
type MockTokenMinter struct {
	mock.Mock
}

type MockTokenMinter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenMinter) EXPECT() *MockTokenMinter_Expecter {
	return &MockTokenMinter_Expecter{mock: &_m.Mock}
}

// MintInstanceToken provides a mock function for the type MockTokenMinter
func (_mock *MockTokenMinter) MintInstanceToken(ctx context.Context, principal string, workloadID string, instance int) (string, error) {
	ret := _mock.Called(ctx, principal, workloadID, instance)

	if len(ret) == 0 {
		panic("no return value specified for MintInstanceToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) (string, error)); ok {
		return returnFunc(ctx, principal, workloadID, instance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) string); ok {
		r0 = returnFunc(ctx, principal, workloadID, instance)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, principal, workloadID, instance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenMinter_MintInstanceToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MintInstanceToken'
type MockTokenMinter_MintInstanceToken_Call struct {
	*mock.Call
}

// MintInstanceToken is a helper method to define mock.On call
//   - ctx context.Context
//   - principal string
//   - workloadID string
//   - instance int
func (_e *MockTokenMinter_Expecter) MintInstanceToken(ctx any, principal any, workloadID any, instance any) *MockTokenMinter_MintInstanceToken_Call {
	return &MockTokenMinter_MintInstanceToken_Call{Call: _e.mock.On("MintInstanceToken", ctx, principal, workloadID, instance)}
}

func (_c *MockTokenMinter_MintInstanceToken_Call) Run(run func(ctx context.Context, principal string, workloadID string, instance int)) *MockTokenMinter_MintInstanceToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTokenMinter_MintInstanceToken_Call) Return(s string, err error) *MockTokenMinter_MintInstanceToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenMinter_MintInstanceToken_Call) RunAndReturn(run func(ctx context.Context, principal string, workloadID string, instance int) (string, error)) *MockTokenMinter_MintInstanceToken_Call {
	_c.Call.Return(run)
	return _c
}
