// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package telemetry_test

import (
	"context"

	"github.com/dsb-labs/takt/internal/server/driver"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// Discard provides a mock function for the type MockDriver
func (_mock *MockDriver) Discard(ctx context.Context, id string, workload string) error {
	ret := _mock.Called(ctx, id, workload)

	if len(ret) == 0 {
		panic("no return value specified for Discard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, workload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_Discard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discard'
type MockDriver_Discard_Call struct {
	*mock.Call
}

// Discard is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workload string
func (_e *MockDriver_Expecter) Discard(ctx any, id any, workload any) *MockDriver_Discard_Call {
	return &MockDriver_Discard_Call{Call: _e.mock.On("Discard", ctx, id, workload)}
}

func (_c *MockDriver_Discard_Call) Run(run func(ctx context.Context, id string, workload string)) *MockDriver_Discard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Discard_Call) Return(err error) *MockDriver_Discard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_Discard_Call) RunAndReturn(run func(ctx context.Context, id string, workload string) error) *MockDriver_Discard_Call {
	_c.Call.Return(run)
	return _c
}

// DiscardInstance provides a mock function for the type MockDriver
func (_mock *MockDriver) DiscardInstance(ctx context.Context, id string, workload string, instance int) error {
	ret := _mock.Called(ctx, id, workload, instance)

	if len(ret) == 0 {
		panic("no return value specified for DiscardInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, id, workload, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_DiscardInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscardInstance'
type MockDriver_DiscardInstance_Call struct {
	*mock.Call
}

// DiscardInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workload string
//   - instance int
func (_e *MockDriver_Expecter) DiscardInstance(ctx any, id any, workload any, instance any) *MockDriver_DiscardInstance_Call {
	return &MockDriver_DiscardInstance_Call{Call: _e.mock.On("DiscardInstance", ctx, id, workload, instance)}
}

func (_c *MockDriver_DiscardInstance_Call) Run(run func(ctx context.Context, id string, workload string, instance int)) *MockDriver_DiscardInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDriver_DiscardInstance_Call) Return(err error) *MockDriver_DiscardInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_DiscardInstance_Call) RunAndReturn(run func(ctx context.Context, id string, workload string, instance int) error) *MockDriver_DiscardInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockDriver
func (_mock *MockDriver) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDriver_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDriver_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDriver_Expecter) Name() *MockDriver_Name_Call {
	return &MockDriver_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDriver_Name_Call) Run(run func()) *MockDriver_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_Name_Call) Return(s string) *MockDriver_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDriver_Name_Call) RunAndReturn(run func() string) *MockDriver_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Observe provides a mock function for the type MockDriver
func (_mock *MockDriver) Observe(ctx context.Context) ([]driver.Instance, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 []driver.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]driver.Instance, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []driver.Instance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]driver.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockDriver_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDriver_Expecter) Observe(ctx any) *MockDriver_Observe_Call {
	return &MockDriver_Observe_Call{Call: _e.mock.On("Observe", ctx)}
}

func (_c *MockDriver_Observe_Call) Run(run func(ctx context.Context)) *MockDriver_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Observe_Call) Return(instances []driver.Instance, err error) *MockDriver_Observe_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *MockDriver_Observe_Call) RunAndReturn(run func(ctx context.Context) ([]driver.Instance, error)) *MockDriver_Observe_Call {
	_c.Call.Return(run)
	return _c
}

// Signal provides a mock function for the type MockDriver
func (_mock *MockDriver) Signal(ctx context.Context, id string, workload string, signal string) error {
	ret := _mock.Called(ctx, id, workload, signal)

	if len(ret) == 0 {
		panic("no return value specified for Signal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, workload, signal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_Signal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signal'
type MockDriver_Signal_Call struct {
	*mock.Call
}

// Signal is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workload string
//   - signal string
func (_e *MockDriver_Expecter) Signal(ctx any, id any, workload any, signal any) *MockDriver_Signal_Call {
	return &MockDriver_Signal_Call{Call: _e.mock.On("Signal", ctx, id, workload, signal)}
}

func (_c *MockDriver_Signal_Call) Run(run func(ctx context.Context, id string, workload string, signal string)) *MockDriver_Signal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDriver_Signal_Call) Return(err error) *MockDriver_Signal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_Signal_Call) RunAndReturn(run func(ctx context.Context, id string, workload string, signal string) error) *MockDriver_Signal_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockDriver
func (_mock *MockDriver) Start(ctx context.Context, w driver.Workload) (string, error) {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, driver.Workload) (string, error)); ok {
		return returnFunc(ctx, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, driver.Workload) string); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, driver.Workload) error); ok {
		r1 = returnFunc(ctx, w)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDriver_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - w driver.Workload
func (_e *MockDriver_Expecter) Start(ctx any, w any) *MockDriver_Start_Call {
	return &MockDriver_Start_Call{Call: _e.mock.On("Start", ctx, w)}
}

func (_c *MockDriver_Start_Call) Run(run func(ctx context.Context, w driver.Workload)) *MockDriver_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 driver.Workload
		if args[1] != nil {
			arg1 = args[1].(driver.Workload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDriver_Start_Call) Return(s string, err error) *MockDriver_Start_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDriver_Start_Call) RunAndReturn(run func(ctx context.Context, w driver.Workload) (string, error)) *MockDriver_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockDriver
func (_mock *MockDriver) Stop(ctx context.Context, id string, workload string) error {
	ret := _mock.Called(ctx, id, workload)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, workload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockDriver_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workload string
func (_e *MockDriver_Expecter) Stop(ctx any, id any, workload any) *MockDriver_Stop_Call {
	return &MockDriver_Stop_Call{Call: _e.mock.On("Stop", ctx, id, workload)}
}

func (_c *MockDriver_Stop_Call) Run(run func(ctx context.Context, id string, workload string)) *MockDriver_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Stop_Call) Return(err error) *MockDriver_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_Stop_Call) RunAndReturn(run func(ctx context.Context, id string, workload string) error) *MockDriver_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// StopInstance provides a mock function for the type MockDriver
func (_mock *MockDriver) StopInstance(ctx context.Context, id string, workload string, instance int) error {
	ret := _mock.Called(ctx, id, workload, instance)

	if len(ret) == 0 {
		panic("no return value specified for StopInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, id, workload, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_StopInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopInstance'
type MockDriver_StopInstance_Call struct {
	*mock.Call
}

// StopInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workload string
//   - instance int
func (_e *MockDriver_Expecter) StopInstance(ctx any, id any, workload any, instance any) *MockDriver_StopInstance_Call {
	return &MockDriver_StopInstance_Call{Call: _e.mock.On("StopInstance", ctx, id, workload, instance)}
}

func (_c *MockDriver_StopInstance_Call) Run(run func(ctx context.Context, id string, workload string, instance int)) *MockDriver_StopInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDriver_StopInstance_Call) Return(err error) *MockDriver_StopInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_StopInstance_Call) RunAndReturn(run func(ctx context.Context, id string, workload string, instance int) error) *MockDriver_StopInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockDriver
func (_mock *MockDriver) Watch(ctx context.Context) (<-chan driver.Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan driver.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan driver.Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan driver.Event); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan driver.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockDriver_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDriver_Expecter) Watch(ctx any) *MockDriver_Watch_Call {
	return &MockDriver_Watch_Call{Call: _e.mock.On("Watch", ctx)}
}

func (_c *MockDriver_Watch_Call) Run(run func(ctx context.Context)) *MockDriver_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Watch_Call) Return(eventCh <-chan driver.Event, err error) *MockDriver_Watch_Call {
	_c.Call.Return(eventCh, err)
	return _c
}

func (_c *MockDriver_Watch_Call) RunAndReturn(run func(ctx context.Context) (<-chan driver.Event, error)) *MockDriver_Watch_Call {
	_c.Call.Return(run)
	return _c
}
