// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package port_test

import (
	"context"

	"github.com/dsb-labs/orca/internal/server/port"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Allocated provides a mock function for the type MockRepository
func (_mock *MockRepository) Allocated(ctx context.Context) (map[string][]int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Allocated")
	}

	var r0 map[string][]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string][]int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string][]int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Allocated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allocated'
type MockRepository_Allocated_Call struct {
	*mock.Call
}

// Allocated is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Allocated(ctx any) *MockRepository_Allocated_Call {
	return &MockRepository_Allocated_Call{Call: _e.mock.On("Allocated", ctx)}
}

func (_c *MockRepository_Allocated_Call) Run(run func(ctx context.Context)) *MockRepository_Allocated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Allocated_Call) Return(stringToInts map[string][]int, err error) *MockRepository_Allocated_Call {
	_c.Call.Return(stringToInts, err)
	return _c
}

func (_c *MockRepository_Allocated_Call) RunAndReturn(run func(ctx context.Context) (map[string][]int, error)) *MockRepository_Allocated_Call {
	_c.Call.Return(run)
	return _c
}

// HolderOf provides a mock function for the type MockRepository
func (_mock *MockRepository) HolderOf(ctx context.Context, host int, protocol string) (string, bool, error) {
	ret := _mock.Called(ctx, host, protocol)

	if len(ret) == 0 {
		panic("no return value specified for HolderOf")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (string, bool, error)); ok {
		return returnFunc(ctx, host, protocol)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) string); ok {
		r0 = returnFunc(ctx, host, protocol)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) bool); ok {
		r1 = returnFunc(ctx, host, protocol)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, string) error); ok {
		r2 = returnFunc(ctx, host, protocol)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_HolderOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HolderOf'
type MockRepository_HolderOf_Call struct {
	*mock.Call
}

// HolderOf is a helper method to define mock.On call
//   - ctx context.Context
//   - host int
//   - protocol string
func (_e *MockRepository_Expecter) HolderOf(ctx any, host any, protocol any) *MockRepository_HolderOf_Call {
	return &MockRepository_HolderOf_Call{Call: _e.mock.On("HolderOf", ctx, host, protocol)}
}

func (_c *MockRepository_HolderOf_Call) Run(run func(ctx context.Context, host int, protocol string)) *MockRepository_HolderOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_HolderOf_Call) Return(s string, b bool, err error) *MockRepository_HolderOf_Call {
	_c.Call.Return(s, b, err)
	return _c
}

func (_c *MockRepository_HolderOf_Call) RunAndReturn(run func(ctx context.Context, host int, protocol string) (string, bool, error)) *MockRepository_HolderOf_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAllocation creates a new instance of MockAllocation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAllocation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAllocation {
	mock := &MockAllocation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAllocation is an autogenerated mock type for the Allocation type
type MockAllocation struct {
	mock.Mock
}

type MockAllocation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAllocation) EXPECT() *MockAllocation_Expecter {
	return &MockAllocation_Expecter{mock: &_m.Mock}
}

// Allocate provides a mock function for the type MockAllocation
func (_mock *MockAllocation) Allocate(protocols []port.Protocol, taken map[port.Protocol][]int) (int, error) {
	ret := _mock.Called(protocols, taken)

	if len(ret) == 0 {
		panic("no return value specified for Allocate")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]port.Protocol, map[port.Protocol][]int) (int, error)); ok {
		return returnFunc(protocols, taken)
	}
	if returnFunc, ok := ret.Get(0).(func([]port.Protocol, map[port.Protocol][]int) int); ok {
		r0 = returnFunc(protocols, taken)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]port.Protocol, map[port.Protocol][]int) error); ok {
		r1 = returnFunc(protocols, taken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAllocation_Allocate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allocate'
type MockAllocation_Allocate_Call struct {
	*mock.Call
}

// Allocate is a helper method to define mock.On call
//   - protocols []port.Protocol
//   - taken map[port.Protocol][]int
func (_e *MockAllocation_Expecter) Allocate(protocols any, taken any) *MockAllocation_Allocate_Call {
	return &MockAllocation_Allocate_Call{Call: _e.mock.On("Allocate", protocols, taken)}
}

func (_c *MockAllocation_Allocate_Call) Run(run func(protocols []port.Protocol, taken map[port.Protocol][]int)) *MockAllocation_Allocate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []port.Protocol
		if args[0] != nil {
			arg0 = args[0].([]port.Protocol)
		}
		var arg1 map[port.Protocol][]int
		if args[1] != nil {
			arg1 = args[1].(map[port.Protocol][]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAllocation_Allocate_Call) Return(n int, err error) *MockAllocation_Allocate_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAllocation_Allocate_Call) RunAndReturn(run func(protocols []port.Protocol, taken map[port.Protocol][]int) (int, error)) *MockAllocation_Allocate_Call {
	_c.Call.Return(run)
	return _c
}
