// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reconciler_test

import (
	"context"

	"github.com/dsb-labs/orca/internal/server/database"
	"github.com/dsb-labs/orca/internal/server/driver"
	"github.com/dsb-labs/orca/internal/server/health"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// Observe provides a mock function for the type MockDriver
func (_mock *MockDriver) Observe(ctx context.Context) ([]driver.Instance, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 []driver.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]driver.Instance, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []driver.Instance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]driver.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockDriver_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDriver_Expecter) Observe(ctx any) *MockDriver_Observe_Call {
	return &MockDriver_Observe_Call{Call: _e.mock.On("Observe", ctx)}
}

func (_c *MockDriver_Observe_Call) Run(run func(ctx context.Context)) *MockDriver_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Observe_Call) Return(instances []driver.Instance, err error) *MockDriver_Observe_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *MockDriver_Observe_Call) RunAndReturn(run func(ctx context.Context) ([]driver.Instance, error)) *MockDriver_Observe_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockDriver
func (_mock *MockDriver) Start(ctx context.Context, w driver.Workload) (string, error) {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, driver.Workload) (string, error)); ok {
		return returnFunc(ctx, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, driver.Workload) string); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, driver.Workload) error); ok {
		r1 = returnFunc(ctx, w)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDriver_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - w driver.Workload
func (_e *MockDriver_Expecter) Start(ctx any, w any) *MockDriver_Start_Call {
	return &MockDriver_Start_Call{Call: _e.mock.On("Start", ctx, w)}
}

func (_c *MockDriver_Start_Call) Run(run func(ctx context.Context, w driver.Workload)) *MockDriver_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 driver.Workload
		if args[1] != nil {
			arg1 = args[1].(driver.Workload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDriver_Start_Call) Return(s string, err error) *MockDriver_Start_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDriver_Start_Call) RunAndReturn(run func(ctx context.Context, w driver.Workload) (string, error)) *MockDriver_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockDriver
func (_mock *MockDriver) Stop(ctx context.Context, workload string) error {
	ret := _mock.Called(ctx, workload)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, workload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockDriver_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - workload string
func (_e *MockDriver_Expecter) Stop(ctx any, workload any) *MockDriver_Stop_Call {
	return &MockDriver_Stop_Call{Call: _e.mock.On("Stop", ctx, workload)}
}

func (_c *MockDriver_Stop_Call) Run(run func(ctx context.Context, workload string)) *MockDriver_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDriver_Stop_Call) Return(err error) *MockDriver_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_Stop_Call) RunAndReturn(run func(ctx context.Context, workload string) error) *MockDriver_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockDriver
func (_mock *MockDriver) Watch(ctx context.Context) (<-chan driver.Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan driver.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan driver.Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan driver.Event); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan driver.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockDriver_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDriver_Expecter) Watch(ctx any) *MockDriver_Watch_Call {
	return &MockDriver_Watch_Call{Call: _e.mock.On("Watch", ctx)}
}

func (_c *MockDriver_Watch_Call) Run(run func(ctx context.Context)) *MockDriver_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Watch_Call) Return(eventCh <-chan driver.Event, err error) *MockDriver_Watch_Call {
	_c.Call.Return(eventCh, err)
	return _c
}

func (_c *MockDriver_Watch_Call) RunAndReturn(run func(ctx context.Context) (<-chan driver.Event, error)) *MockDriver_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkloadRepository creates a new instance of MockWorkloadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkloadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkloadRepository {
	mock := &MockWorkloadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkloadRepository is an autogenerated mock type for the WorkloadRepository type
type MockWorkloadRepository struct {
	mock.Mock
}

type MockWorkloadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkloadRepository) EXPECT() *MockWorkloadRepository_Expecter {
	return &MockWorkloadRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkloadRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWorkloadRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadRepository_Expecter) Delete(ctx any, name any) *MockWorkloadRepository_Delete_Call {
	return &MockWorkloadRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockWorkloadRepository_Delete_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_Delete_Call) Return(err error) *MockWorkloadRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkloadRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockWorkloadRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) List(ctx context.Context, queries ...database.Query) ([]database.Workload, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...database.Query) ([]database.Workload, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...database.Query) []database.Workload); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...database.Query) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkloadRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...database.Query
func (_e *MockWorkloadRepository_Expecter) List(ctx any, queries ...any) *MockWorkloadRepository_List_Call {
	return &MockWorkloadRepository_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockWorkloadRepository_List_Call) Run(run func(ctx context.Context, queries ...database.Query)) *MockWorkloadRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []database.Query
		var variadicArgs []database.Query
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Query)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_List_Call) Return(workloads []database.Workload, err error) *MockWorkloadRepository_List_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *MockWorkloadRepository_List_Call) RunAndReturn(run func(ctx context.Context, queries ...database.Query) ([]database.Workload, error)) *MockWorkloadRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPortRepository creates a new instance of MockPortRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPortRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPortRepository {
	mock := &MockPortRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPortRepository is an autogenerated mock type for the PortRepository type
type MockPortRepository struct {
	mock.Mock
}

type MockPortRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPortRepository) EXPECT() *MockPortRepository_Expecter {
	return &MockPortRepository_Expecter{mock: &_m.Mock}
}

// ListAll provides a mock function for the type MockPortRepository
func (_mock *MockPortRepository) ListAll(ctx context.Context) (map[string][]database.Port, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 map[string][]database.Port
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string][]database.Port, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string][]database.Port); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]database.Port)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockPortRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPortRepository_Expecter) ListAll(ctx any) *MockPortRepository_ListAll_Call {
	return &MockPortRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockPortRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockPortRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPortRepository_ListAll_Call) Return(stringToPorts map[string][]database.Port, err error) *MockPortRepository_ListAll_Call {
	_c.Call.Return(stringToPorts, err)
	return _c
}

func (_c *MockPortRepository_ListAll_Call) RunAndReturn(run func(ctx context.Context) (map[string][]database.Port, error)) *MockPortRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

type MockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecker) EXPECT() *MockChecker_Expecter {
	return &MockChecker_Expecter{mock: &_m.Mock}
}

// Forget provides a mock function for the type MockChecker
func (_mock *MockChecker) Forget(workload string) {
	_mock.Called(workload)
	return
}

// MockChecker_Forget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forget'
type MockChecker_Forget_Call struct {
	*mock.Call
}

// Forget is a helper method to define mock.On call
//   - workload string
func (_e *MockChecker_Expecter) Forget(workload any) *MockChecker_Forget_Call {
	return &MockChecker_Forget_Call{Call: _e.mock.On("Forget", workload)}
}

func (_c *MockChecker_Forget_Call) Run(run func(workload string)) *MockChecker_Forget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChecker_Forget_Call) Return() *MockChecker_Forget_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChecker_Forget_Call) RunAndReturn(run func(workload string)) *MockChecker_Forget_Call {
	_c.Run(run)
	return _c
}

// Result provides a mock function for the type MockChecker
func (_mock *MockChecker) Result(workload string) (health.Result, bool) {
	ret := _mock.Called(workload)

	if len(ret) == 0 {
		panic("no return value specified for Result")
	}

	var r0 health.Result
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (health.Result, bool)); ok {
		return returnFunc(workload)
	}
	if returnFunc, ok := ret.Get(0).(func(string) health.Result); ok {
		r0 = returnFunc(workload)
	} else {
		r0 = ret.Get(0).(health.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(workload)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockChecker_Result_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Result'
type MockChecker_Result_Call struct {
	*mock.Call
}

// Result is a helper method to define mock.On call
//   - workload string
func (_e *MockChecker_Expecter) Result(workload any) *MockChecker_Result_Call {
	return &MockChecker_Result_Call{Call: _e.mock.On("Result", workload)}
}

func (_c *MockChecker_Result_Call) Run(run func(workload string)) *MockChecker_Result_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChecker_Result_Call) Return(result health.Result, b bool) *MockChecker_Result_Call {
	_c.Call.Return(result, b)
	return _c
}

func (_c *MockChecker_Result_Call) RunAndReturn(run func(workload string) (health.Result, bool)) *MockChecker_Result_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockChecker
func (_mock *MockChecker) Set(workload string, check health.Check) {
	_mock.Called(workload, check)
	return
}

// MockChecker_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockChecker_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - workload string
//   - check health.Check
func (_e *MockChecker_Expecter) Set(workload any, check any) *MockChecker_Set_Call {
	return &MockChecker_Set_Call{Call: _e.mock.On("Set", workload, check)}
}

func (_c *MockChecker_Set_Call) Run(run func(workload string, check health.Check)) *MockChecker_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 health.Check
		if args[1] != nil {
			arg1 = args[1].(health.Check)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChecker_Set_Call) Return() *MockChecker_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChecker_Set_Call) RunAndReturn(run func(workload string, check health.Check)) *MockChecker_Set_Call {
	_c.Run(run)
	return _c
}
