// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reconciler_test

import (
	"context"

	"github.com/dsb-labs/orca/internal/server/database"
	"github.com/dsb-labs/orca/internal/server/driver"
	"github.com/dsb-labs/orca/internal/server/health"
	"github.com/dsb-labs/orca/internal/server/service"
	"github.com/dsb-labs/orca/pkg/manifest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// Discard provides a mock function for the type MockDriver
func (_mock *MockDriver) Discard(ctx context.Context, id string, workload string) error {
	ret := _mock.Called(ctx, id, workload)

	if len(ret) == 0 {
		panic("no return value specified for Discard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, workload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_Discard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discard'
type MockDriver_Discard_Call struct {
	*mock.Call
}

// Discard is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workload string
func (_e *MockDriver_Expecter) Discard(ctx any, id any, workload any) *MockDriver_Discard_Call {
	return &MockDriver_Discard_Call{Call: _e.mock.On("Discard", ctx, id, workload)}
}

func (_c *MockDriver_Discard_Call) Run(run func(ctx context.Context, id string, workload string)) *MockDriver_Discard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Discard_Call) Return(err error) *MockDriver_Discard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_Discard_Call) RunAndReturn(run func(ctx context.Context, id string, workload string) error) *MockDriver_Discard_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockDriver
func (_mock *MockDriver) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDriver_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDriver_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDriver_Expecter) Name() *MockDriver_Name_Call {
	return &MockDriver_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDriver_Name_Call) Run(run func()) *MockDriver_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_Name_Call) Return(s string) *MockDriver_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDriver_Name_Call) RunAndReturn(run func() string) *MockDriver_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Observe provides a mock function for the type MockDriver
func (_mock *MockDriver) Observe(ctx context.Context) ([]driver.Instance, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 []driver.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]driver.Instance, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []driver.Instance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]driver.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockDriver_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDriver_Expecter) Observe(ctx any) *MockDriver_Observe_Call {
	return &MockDriver_Observe_Call{Call: _e.mock.On("Observe", ctx)}
}

func (_c *MockDriver_Observe_Call) Run(run func(ctx context.Context)) *MockDriver_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Observe_Call) Return(instances []driver.Instance, err error) *MockDriver_Observe_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *MockDriver_Observe_Call) RunAndReturn(run func(ctx context.Context) ([]driver.Instance, error)) *MockDriver_Observe_Call {
	_c.Call.Return(run)
	return _c
}

// Signal provides a mock function for the type MockDriver
func (_mock *MockDriver) Signal(ctx context.Context, id string, workload string, signal string) error {
	ret := _mock.Called(ctx, id, workload, signal)

	if len(ret) == 0 {
		panic("no return value specified for Signal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, workload, signal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_Signal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signal'
type MockDriver_Signal_Call struct {
	*mock.Call
}

// Signal is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workload string
//   - signal string
func (_e *MockDriver_Expecter) Signal(ctx any, id any, workload any, signal any) *MockDriver_Signal_Call {
	return &MockDriver_Signal_Call{Call: _e.mock.On("Signal", ctx, id, workload, signal)}
}

func (_c *MockDriver_Signal_Call) Run(run func(ctx context.Context, id string, workload string, signal string)) *MockDriver_Signal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDriver_Signal_Call) Return(err error) *MockDriver_Signal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_Signal_Call) RunAndReturn(run func(ctx context.Context, id string, workload string, signal string) error) *MockDriver_Signal_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockDriver
func (_mock *MockDriver) Start(ctx context.Context, w driver.Workload) (string, error) {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, driver.Workload) (string, error)); ok {
		return returnFunc(ctx, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, driver.Workload) string); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, driver.Workload) error); ok {
		r1 = returnFunc(ctx, w)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDriver_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - w driver.Workload
func (_e *MockDriver_Expecter) Start(ctx any, w any) *MockDriver_Start_Call {
	return &MockDriver_Start_Call{Call: _e.mock.On("Start", ctx, w)}
}

func (_c *MockDriver_Start_Call) Run(run func(ctx context.Context, w driver.Workload)) *MockDriver_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 driver.Workload
		if args[1] != nil {
			arg1 = args[1].(driver.Workload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDriver_Start_Call) Return(s string, err error) *MockDriver_Start_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDriver_Start_Call) RunAndReturn(run func(ctx context.Context, w driver.Workload) (string, error)) *MockDriver_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockDriver
func (_mock *MockDriver) Stop(ctx context.Context, id string, workload string) error {
	ret := _mock.Called(ctx, id, workload)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, workload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockDriver_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workload string
func (_e *MockDriver_Expecter) Stop(ctx any, id any, workload any) *MockDriver_Stop_Call {
	return &MockDriver_Stop_Call{Call: _e.mock.On("Stop", ctx, id, workload)}
}

func (_c *MockDriver_Stop_Call) Run(run func(ctx context.Context, id string, workload string)) *MockDriver_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Stop_Call) Return(err error) *MockDriver_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_Stop_Call) RunAndReturn(run func(ctx context.Context, id string, workload string) error) *MockDriver_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockDriver
func (_mock *MockDriver) Watch(ctx context.Context) (<-chan driver.Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan driver.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan driver.Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan driver.Event); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan driver.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockDriver_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDriver_Expecter) Watch(ctx any) *MockDriver_Watch_Call {
	return &MockDriver_Watch_Call{Call: _e.mock.On("Watch", ctx)}
}

func (_c *MockDriver_Watch_Call) Run(run func(ctx context.Context)) *MockDriver_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Watch_Call) Return(eventCh <-chan driver.Event, err error) *MockDriver_Watch_Call {
	_c.Call.Return(eventCh, err)
	return _c
}

func (_c *MockDriver_Watch_Call) RunAndReturn(run func(ctx context.Context) (<-chan driver.Event, error)) *MockDriver_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkloadRepository creates a new instance of MockWorkloadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkloadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkloadRepository {
	mock := &MockWorkloadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkloadRepository is an autogenerated mock type for the WorkloadRepository type
type MockWorkloadRepository struct {
	mock.Mock
}

type MockWorkloadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkloadRepository) EXPECT() *MockWorkloadRepository_Expecter {
	return &MockWorkloadRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkloadRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWorkloadRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadRepository_Expecter) Delete(ctx any, name any) *MockWorkloadRepository_Delete_Call {
	return &MockWorkloadRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockWorkloadRepository_Delete_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_Delete_Call) Return(err error) *MockWorkloadRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkloadRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockWorkloadRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkloadRepository
func (_mock *MockWorkloadRepository) List(ctx context.Context, queries ...database.Query) ([]database.Workload, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...database.Query) ([]database.Workload, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...database.Query) []database.Workload); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...database.Query) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkloadRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...database.Query
func (_e *MockWorkloadRepository_Expecter) List(ctx any, queries ...any) *MockWorkloadRepository_List_Call {
	return &MockWorkloadRepository_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockWorkloadRepository_List_Call) Run(run func(ctx context.Context, queries ...database.Query)) *MockWorkloadRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []database.Query
		var variadicArgs []database.Query
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Query)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWorkloadRepository_List_Call) Return(workloads []database.Workload, err error) *MockWorkloadRepository_List_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *MockWorkloadRepository_List_Call) RunAndReturn(run func(ctx context.Context, queries ...database.Query) ([]database.Workload, error)) *MockWorkloadRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPortRepository creates a new instance of MockPortRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPortRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPortRepository {
	mock := &MockPortRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPortRepository is an autogenerated mock type for the PortRepository type
type MockPortRepository struct {
	mock.Mock
}

type MockPortRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPortRepository) EXPECT() *MockPortRepository_Expecter {
	return &MockPortRepository_Expecter{mock: &_m.Mock}
}

// ListAll provides a mock function for the type MockPortRepository
func (_mock *MockPortRepository) ListAll(ctx context.Context) (map[string][]database.Port, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 map[string][]database.Port
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string][]database.Port, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string][]database.Port); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]database.Port)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockPortRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPortRepository_Expecter) ListAll(ctx any) *MockPortRepository_ListAll_Call {
	return &MockPortRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockPortRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockPortRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPortRepository_ListAll_Call) Return(stringToPorts map[string][]database.Port, err error) *MockPortRepository_ListAll_Call {
	_c.Call.Return(stringToPorts, err)
	return _c
}

func (_c *MockPortRepository_ListAll_Call) RunAndReturn(run func(ctx context.Context) (map[string][]database.Port, error)) *MockPortRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockResolver
func (_mock *MockResolver) Resolve(ctx context.Context, env map[string]string, reader string, readerInstance int) (map[string]string, error) {
	ret := _mock.Called(ctx, env, reader, readerInstance)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, string, int) (map[string]string, error)); ok {
		return returnFunc(ctx, env, reader, readerInstance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, string, int) map[string]string); ok {
		r0 = returnFunc(ctx, env, reader, readerInstance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string, string, int) error); ok {
		r1 = returnFunc(ctx, env, reader, readerInstance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - env map[string]string
//   - reader string
//   - readerInstance int
func (_e *MockResolver_Expecter) Resolve(ctx any, env any, reader any, readerInstance any) *MockResolver_Resolve_Call {
	return &MockResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, env, reader, readerInstance)}
}

func (_c *MockResolver_Resolve_Call) Run(run func(ctx context.Context, env map[string]string, reader string, readerInstance int)) *MockResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResolver_Resolve_Call) Return(stringToString map[string]string, err error) *MockResolver_Resolve_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context, env map[string]string, reader string, readerInstance int) (map[string]string, error)) *MockResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMounts creates a new instance of MockMounts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMounts(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMounts {
	mock := &MockMounts{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMounts is an autogenerated mock type for the Mounts type
type MockMounts struct {
	mock.Mock
}

type MockMounts_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMounts) EXPECT() *MockMounts_Expecter {
	return &MockMounts_Expecter{mock: &_m.Mock}
}

// Deliver provides a mock function for the type MockMounts
func (_mock *MockMounts) Deliver(ctx context.Context, id string, version int, spec manifest.Spec) ([]driver.Volume, error) {
	ret := _mock.Called(ctx, id, version, spec)

	if len(ret) == 0 {
		panic("no return value specified for Deliver")
	}

	var r0 []driver.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, manifest.Spec) ([]driver.Volume, error)); ok {
		return returnFunc(ctx, id, version, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, manifest.Spec) []driver.Volume); ok {
		r0 = returnFunc(ctx, id, version, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]driver.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, manifest.Spec) error); ok {
		r1 = returnFunc(ctx, id, version, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMounts_Deliver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deliver'
type MockMounts_Deliver_Call struct {
	*mock.Call
}

// Deliver is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - version int
//   - spec manifest.Spec
func (_e *MockMounts_Expecter) Deliver(ctx any, id any, version any, spec any) *MockMounts_Deliver_Call {
	return &MockMounts_Deliver_Call{Call: _e.mock.On("Deliver", ctx, id, version, spec)}
}

func (_c *MockMounts_Deliver_Call) Run(run func(ctx context.Context, id string, version int, spec manifest.Spec)) *MockMounts_Deliver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 manifest.Spec
		if args[3] != nil {
			arg3 = args[3].(manifest.Spec)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMounts_Deliver_Call) Return(volumes []driver.Volume, err error) *MockMounts_Deliver_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *MockMounts_Deliver_Call) RunAndReturn(run func(ctx context.Context, id string, version int, spec manifest.Spec) ([]driver.Volume, error)) *MockMounts_Deliver_Call {
	_c.Call.Return(run)
	return _c
}

// Forget provides a mock function for the type MockMounts
func (_mock *MockMounts) Forget(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Forget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMounts_Forget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forget'
type MockMounts_Forget_Call struct {
	*mock.Call
}

// Forget is a helper method to define mock.On call
//   - id string
func (_e *MockMounts_Expecter) Forget(id any) *MockMounts_Forget_Call {
	return &MockMounts_Forget_Call{Call: _e.mock.On("Forget", id)}
}

func (_c *MockMounts_Forget_Call) Run(run func(id string)) *MockMounts_Forget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMounts_Forget_Call) Return(err error) *MockMounts_Forget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMounts_Forget_Call) RunAndReturn(run func(id string) error) *MockMounts_Forget_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function for the type MockMounts
func (_mock *MockMounts) Prune(keep []string) error {
	ret := _mock.Called(keep)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string) error); ok {
		r0 = returnFunc(keep)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMounts_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type MockMounts_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - keep []string
func (_e *MockMounts_Expecter) Prune(keep any) *MockMounts_Prune_Call {
	return &MockMounts_Prune_Call{Call: _e.mock.On("Prune", keep)}
}

func (_c *MockMounts_Prune_Call) Run(run func(keep []string)) *MockMounts_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMounts_Prune_Call) Return(err error) *MockMounts_Prune_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMounts_Prune_Call) RunAndReturn(run func(keep []string) error) *MockMounts_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// Reclaim provides a mock function for the type MockMounts
func (_mock *MockMounts) Reclaim(id string, keep int) error {
	ret := _mock.Called(id, keep)

	if len(ret) == 0 {
		panic("no return value specified for Reclaim")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = returnFunc(id, keep)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMounts_Reclaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reclaim'
type MockMounts_Reclaim_Call struct {
	*mock.Call
}

// Reclaim is a helper method to define mock.On call
//   - id string
//   - keep int
func (_e *MockMounts_Expecter) Reclaim(id any, keep any) *MockMounts_Reclaim_Call {
	return &MockMounts_Reclaim_Call{Call: _e.mock.On("Reclaim", id, keep)}
}

func (_c *MockMounts_Reclaim_Call) Run(run func(id string, keep int)) *MockMounts_Reclaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMounts_Reclaim_Call) Return(err error) *MockMounts_Reclaim_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMounts_Reclaim_Call) RunAndReturn(run func(id string, keep int) error) *MockMounts_Reclaim_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockMounts
func (_mock *MockMounts) Refresh(ctx context.Context, name string, id string, version int, spec manifest.Spec) ([]service.Refresh, error) {
	ret := _mock.Called(ctx, name, id, version, spec)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 []service.Refresh
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, manifest.Spec) ([]service.Refresh, error)); ok {
		return returnFunc(ctx, name, id, version, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, manifest.Spec) []service.Refresh); ok {
		r0 = returnFunc(ctx, name, id, version, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Refresh)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, manifest.Spec) error); ok {
		r1 = returnFunc(ctx, name, id, version, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMounts_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockMounts_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - id string
//   - version int
//   - spec manifest.Spec
func (_e *MockMounts_Expecter) Refresh(ctx any, name any, id any, version any, spec any) *MockMounts_Refresh_Call {
	return &MockMounts_Refresh_Call{Call: _e.mock.On("Refresh", ctx, name, id, version, spec)}
}

func (_c *MockMounts_Refresh_Call) Run(run func(ctx context.Context, name string, id string, version int, spec manifest.Spec)) *MockMounts_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 manifest.Spec
		if args[4] != nil {
			arg4 = args[4].(manifest.Spec)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMounts_Refresh_Call) Return(refreshs []service.Refresh, err error) *MockMounts_Refresh_Call {
	_c.Call.Return(refreshs, err)
	return _c
}

func (_c *MockMounts_Refresh_Call) RunAndReturn(run func(ctx context.Context, name string, id string, version int, spec manifest.Spec) ([]service.Refresh, error)) *MockMounts_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

type MockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecker) EXPECT() *MockChecker_Expecter {
	return &MockChecker_Expecter{mock: &_m.Mock}
}

// Forget provides a mock function for the type MockChecker
func (_mock *MockChecker) Forget(workload string) {
	_mock.Called(workload)
	return
}

// MockChecker_Forget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forget'
type MockChecker_Forget_Call struct {
	*mock.Call
}

// Forget is a helper method to define mock.On call
//   - workload string
func (_e *MockChecker_Expecter) Forget(workload any) *MockChecker_Forget_Call {
	return &MockChecker_Forget_Call{Call: _e.mock.On("Forget", workload)}
}

func (_c *MockChecker_Forget_Call) Run(run func(workload string)) *MockChecker_Forget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChecker_Forget_Call) Return() *MockChecker_Forget_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChecker_Forget_Call) RunAndReturn(run func(workload string)) *MockChecker_Forget_Call {
	_c.Run(run)
	return _c
}

// Result provides a mock function for the type MockChecker
func (_mock *MockChecker) Result(workload string, instance int) (health.Result, bool) {
	ret := _mock.Called(workload, instance)

	if len(ret) == 0 {
		panic("no return value specified for Result")
	}

	var r0 health.Result
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, int) (health.Result, bool)); ok {
		return returnFunc(workload, instance)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) health.Result); ok {
		r0 = returnFunc(workload, instance)
	} else {
		r0 = ret.Get(0).(health.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) bool); ok {
		r1 = returnFunc(workload, instance)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockChecker_Result_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Result'
type MockChecker_Result_Call struct {
	*mock.Call
}

// Result is a helper method to define mock.On call
//   - workload string
//   - instance int
func (_e *MockChecker_Expecter) Result(workload any, instance any) *MockChecker_Result_Call {
	return &MockChecker_Result_Call{Call: _e.mock.On("Result", workload, instance)}
}

func (_c *MockChecker_Result_Call) Run(run func(workload string, instance int)) *MockChecker_Result_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChecker_Result_Call) Return(result health.Result, b bool) *MockChecker_Result_Call {
	_c.Call.Return(result, b)
	return _c
}

func (_c *MockChecker_Result_Call) RunAndReturn(run func(workload string, instance int) (health.Result, bool)) *MockChecker_Result_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockChecker
func (_mock *MockChecker) Set(workload string, instance int, check health.Check) {
	_mock.Called(workload, instance, check)
	return
}

// MockChecker_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockChecker_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - workload string
//   - instance int
//   - check health.Check
func (_e *MockChecker_Expecter) Set(workload any, instance any, check any) *MockChecker_Set_Call {
	return &MockChecker_Set_Call{Call: _e.mock.On("Set", workload, instance, check)}
}

func (_c *MockChecker_Set_Call) Run(run func(workload string, instance int, check health.Check)) *MockChecker_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 health.Check
		if args[2] != nil {
			arg2 = args[2].(health.Check)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChecker_Set_Call) Return() *MockChecker_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChecker_Set_Call) RunAndReturn(run func(workload string, instance int, check health.Check)) *MockChecker_Set_Call {
	_c.Run(run)
	return _c
}
