ALTER TABLE policy ADD COLUMN etag TEXT NOT NULL DEFAULT '';

ALTER TABLE policy DROP COLUMN version;

ALTER TABLE variable DROP COLUMN version;

ALTER TABLE secret DROP COLUMN version;

ALTER TABLE service DROP COLUMN version;

ALTER TABLE volume DROP COLUMN version;

ALTER TABLE volume DROP COLUMN updated_at;
