// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api_test

import (
	"context"
	"io"

	"github.com/dsb-labs/orca/internal/generated/api"
	"github.com/dsb-labs/orca/internal/server/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretService creates a new instance of MockSecretService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretService {
	mock := &MockSecretService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretService is an autogenerated mock type for the SecretService type
type MockSecretService struct {
	mock.Mock
}

type MockSecretService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretService) EXPECT() *MockSecretService_Expecter {
	return &MockSecretService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSecretService
func (_mock *MockSecretService) Delete(ctx context.Context, name string, force bool) error {
	ret := _mock.Called(ctx, name, force)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, name, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - force bool
func (_e *MockSecretService_Expecter) Delete(ctx any, name any, force any) *MockSecretService_Delete_Call {
	return &MockSecretService_Delete_Call{Call: _e.mock.On("Delete", ctx, name, force)}
}

func (_c *MockSecretService_Delete_Call) Run(run func(ctx context.Context, name string, force bool)) *MockSecretService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretService_Delete_Call) Return(err error) *MockSecretService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, force bool) error) *MockSecretService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSecretService
func (_mock *MockSecretService) Get(ctx context.Context, name string) (service.Secret, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Secret, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Secret); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSecretService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSecretService_Expecter) Get(ctx any, name any) *MockSecretService_Get_Call {
	return &MockSecretService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockSecretService_Get_Call) Run(run func(ctx context.Context, name string)) *MockSecretService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretService_Get_Call) Return(secret service.Secret, err error) *MockSecretService_Get_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Secret, error)) *MockSecretService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSecretService
func (_mock *MockSecretService) List(ctx context.Context) ([]service.Secret, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]service.Secret, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []service.Secret); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSecretService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSecretService_Expecter) List(ctx any) *MockSecretService_List_Call {
	return &MockSecretService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockSecretService_List_Call) Run(run func(ctx context.Context)) *MockSecretService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecretService_List_Call) Return(secrets []service.Secret, err error) *MockSecretService_List_Call {
	_c.Call.Return(secrets, err)
	return _c
}

func (_c *MockSecretService_List_Call) RunAndReturn(run func(ctx context.Context) ([]service.Secret, error)) *MockSecretService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockSecretService
func (_mock *MockSecretService) Set(ctx context.Context, name string, value []byte) (service.Secret, bool, error) {
	ret := _mock.Called(ctx, name, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 service.Secret
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (service.Secret, bool, error)); ok {
		return returnFunc(ctx, name, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) service.Secret); ok {
		r0 = returnFunc(ctx, name, value)
	} else {
		r0 = ret.Get(0).(service.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) bool); ok {
		r1 = returnFunc(ctx, name, value)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []byte) error); ok {
		r2 = returnFunc(ctx, name, value)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSecretService_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSecretService_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value []byte
func (_e *MockSecretService_Expecter) Set(ctx any, name any, value any) *MockSecretService_Set_Call {
	return &MockSecretService_Set_Call{Call: _e.mock.On("Set", ctx, name, value)}
}

func (_c *MockSecretService_Set_Call) Run(run func(ctx context.Context, name string, value []byte)) *MockSecretService_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretService_Set_Call) Return(secret service.Secret, b bool, err error) *MockSecretService_Set_Call {
	_c.Call.Return(secret, b, err)
	return _c
}

func (_c *MockSecretService_Set_Call) RunAndReturn(run func(ctx context.Context, name string, value []byte) (service.Secret, bool, error)) *MockSecretService_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVariableService creates a new instance of MockVariableService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVariableService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVariableService {
	mock := &MockVariableService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVariableService is an autogenerated mock type for the VariableService type
type MockVariableService struct {
	mock.Mock
}

type MockVariableService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVariableService) EXPECT() *MockVariableService_Expecter {
	return &MockVariableService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockVariableService
func (_mock *MockVariableService) Delete(ctx context.Context, name string, force bool) error {
	ret := _mock.Called(ctx, name, force)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, name, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVariableService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVariableService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - force bool
func (_e *MockVariableService_Expecter) Delete(ctx any, name any, force any) *MockVariableService_Delete_Call {
	return &MockVariableService_Delete_Call{Call: _e.mock.On("Delete", ctx, name, force)}
}

func (_c *MockVariableService_Delete_Call) Run(run func(ctx context.Context, name string, force bool)) *MockVariableService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVariableService_Delete_Call) Return(err error) *MockVariableService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVariableService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, force bool) error) *MockVariableService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockVariableService
func (_mock *MockVariableService) Get(ctx context.Context, name string) (service.Variable, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Variable
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Variable, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Variable); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Variable)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVariableService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVariableService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockVariableService_Expecter) Get(ctx any, name any) *MockVariableService_Get_Call {
	return &MockVariableService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockVariableService_Get_Call) Run(run func(ctx context.Context, name string)) *MockVariableService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVariableService_Get_Call) Return(variable service.Variable, err error) *MockVariableService_Get_Call {
	_c.Call.Return(variable, err)
	return _c
}

func (_c *MockVariableService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Variable, error)) *MockVariableService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVariableService
func (_mock *MockVariableService) List(ctx context.Context) ([]service.Variable, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Variable
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]service.Variable, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []service.Variable); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Variable)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVariableService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVariableService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVariableService_Expecter) List(ctx any) *MockVariableService_List_Call {
	return &MockVariableService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockVariableService_List_Call) Run(run func(ctx context.Context)) *MockVariableService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVariableService_List_Call) Return(variables []service.Variable, err error) *MockVariableService_List_Call {
	_c.Call.Return(variables, err)
	return _c
}

func (_c *MockVariableService_List_Call) RunAndReturn(run func(ctx context.Context) ([]service.Variable, error)) *MockVariableService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockVariableService
func (_mock *MockVariableService) Set(ctx context.Context, name string, value string) (service.Variable, bool, error) {
	ret := _mock.Called(ctx, name, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 service.Variable
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (service.Variable, bool, error)); ok {
		return returnFunc(ctx, name, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) service.Variable); ok {
		r0 = returnFunc(ctx, name, value)
	} else {
		r0 = ret.Get(0).(service.Variable)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, name, value)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, name, value)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockVariableService_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockVariableService_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value string
func (_e *MockVariableService_Expecter) Set(ctx any, name any, value any) *MockVariableService_Set_Call {
	return &MockVariableService_Set_Call{Call: _e.mock.On("Set", ctx, name, value)}
}

func (_c *MockVariableService_Set_Call) Run(run func(ctx context.Context, name string, value string)) *MockVariableService_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVariableService_Set_Call) Return(variable service.Variable, b bool, err error) *MockVariableService_Set_Call {
	_c.Call.Return(variable, b, err)
	return _c
}

func (_c *MockVariableService_Set_Call) RunAndReturn(run func(ctx context.Context, name string, value string) (service.Variable, bool, error)) *MockVariableService_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVolumeService creates a new instance of MockVolumeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeService {
	mock := &MockVolumeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVolumeService is an autogenerated mock type for the VolumeService type
type MockVolumeService struct {
	mock.Mock
}

type MockVolumeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeService) EXPECT() *MockVolumeService_Expecter {
	return &MockVolumeService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) Create(ctx context.Context, name string) (service.Volume, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 service.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Volume, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Volume); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Volume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVolumeService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockVolumeService_Expecter) Create(ctx any, name any) *MockVolumeService_Create_Call {
	return &MockVolumeService_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *MockVolumeService_Create_Call) Run(run func(ctx context.Context, name string)) *MockVolumeService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVolumeService_Create_Call) Return(volume service.Volume, err error) *MockVolumeService_Create_Call {
	_c.Call.Return(volume, err)
	return _c
}

func (_c *MockVolumeService_Create_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Volume, error)) *MockVolumeService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) Delete(ctx context.Context, name string, force bool) error {
	ret := _mock.Called(ctx, name, force)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, name, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVolumeService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVolumeService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - force bool
func (_e *MockVolumeService_Expecter) Delete(ctx any, name any, force any) *MockVolumeService_Delete_Call {
	return &MockVolumeService_Delete_Call{Call: _e.mock.On("Delete", ctx, name, force)}
}

func (_c *MockVolumeService_Delete_Call) Run(run func(ctx context.Context, name string, force bool)) *MockVolumeService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVolumeService_Delete_Call) Return(err error) *MockVolumeService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVolumeService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, force bool) error) *MockVolumeService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) Get(ctx context.Context, name string) (service.Volume, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Volume, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Volume); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Volume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVolumeService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockVolumeService_Expecter) Get(ctx any, name any) *MockVolumeService_Get_Call {
	return &MockVolumeService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockVolumeService_Get_Call) Run(run func(ctx context.Context, name string)) *MockVolumeService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVolumeService_Get_Call) Return(volume service.Volume, err error) *MockVolumeService_Get_Call {
	_c.Call.Return(volume, err)
	return _c
}

func (_c *MockVolumeService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Volume, error)) *MockVolumeService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) List(ctx context.Context) ([]service.Volume, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]service.Volume, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []service.Volume); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVolumeService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVolumeService_Expecter) List(ctx any) *MockVolumeService_List_Call {
	return &MockVolumeService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockVolumeService_List_Call) Run(run func(ctx context.Context)) *MockVolumeService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVolumeService_List_Call) Return(volumes []service.Volume, err error) *MockVolumeService_List_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *MockVolumeService_List_Call) RunAndReturn(run func(ctx context.Context) ([]service.Volume, error)) *MockVolumeService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkloadService creates a new instance of MockWorkloadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkloadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkloadService {
	mock := &MockWorkloadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkloadService is an autogenerated mock type for the WorkloadService type
type MockWorkloadService struct {
	mock.Mock
}

type MockWorkloadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkloadService) EXPECT() *MockWorkloadService_Expecter {
	return &MockWorkloadService_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Apply(ctx context.Context, spec api.WorkloadSpec) (service.Workload, bool, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 service.Workload
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.WorkloadSpec) (service.Workload, bool, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.WorkloadSpec) service.Workload); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, api.WorkloadSpec) bool); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, api.WorkloadSpec) error); ok {
		r2 = returnFunc(ctx, spec)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWorkloadService_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockWorkloadService_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - spec api.WorkloadSpec
func (_e *MockWorkloadService_Expecter) Apply(ctx any, spec any) *MockWorkloadService_Apply_Call {
	return &MockWorkloadService_Apply_Call{Call: _e.mock.On("Apply", ctx, spec)}
}

func (_c *MockWorkloadService_Apply_Call) Run(run func(ctx context.Context, spec api.WorkloadSpec)) *MockWorkloadService_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 api.WorkloadSpec
		if args[1] != nil {
			arg1 = args[1].(api.WorkloadSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Apply_Call) Return(workload service.Workload, b bool, err error) *MockWorkloadService_Apply_Call {
	_c.Call.Return(workload, b, err)
	return _c
}

func (_c *MockWorkloadService_Apply_Call) RunAndReturn(run func(ctx context.Context, spec api.WorkloadSpec) (service.Workload, bool, error)) *MockWorkloadService_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Delete(ctx context.Context, name string) (service.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWorkloadService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadService_Expecter) Delete(ctx any, name any) *MockWorkloadService_Delete_Call {
	return &MockWorkloadService_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockWorkloadService_Delete_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Delete_Call) Return(workload service.Workload, err error) *MockWorkloadService_Delete_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Workload, error)) *MockWorkloadService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Get(ctx context.Context, name string) (service.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkloadService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadService_Expecter) Get(ctx any, name any) *MockWorkloadService_Get_Call {
	return &MockWorkloadService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockWorkloadService_Get_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Get_Call) Return(workload service.Workload, err error) *MockWorkloadService_Get_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Workload, error)) *MockWorkloadService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) List(ctx context.Context, queries ...string) ([]service.Workload, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]service.Workload, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []service.Workload); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkloadService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockWorkloadService_Expecter) List(ctx any, queries ...any) *MockWorkloadService_List_Call {
	return &MockWorkloadService_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockWorkloadService_List_Call) Run(run func(ctx context.Context, queries ...string)) *MockWorkloadService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWorkloadService_List_Call) Return(workloads []service.Workload, err error) *MockWorkloadService_List_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *MockWorkloadService_List_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]service.Workload, error)) *MockWorkloadService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Logs(ctx context.Context, out io.Writer, name string, tail int) error {
	ret := _mock.Called(ctx, out, name, tail)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Writer, string, int) error); ok {
		r0 = returnFunc(ctx, out, name, tail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkloadService_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type MockWorkloadService_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - out io.Writer
//   - name string
//   - tail int
func (_e *MockWorkloadService_Expecter) Logs(ctx any, out any, name any, tail any) *MockWorkloadService_Logs_Call {
	return &MockWorkloadService_Logs_Call{Call: _e.mock.On("Logs", ctx, out, name, tail)}
}

func (_c *MockWorkloadService_Logs_Call) Run(run func(ctx context.Context, out io.Writer, name string, tail int)) *MockWorkloadService_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Logs_Call) Return(err error) *MockWorkloadService_Logs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkloadService_Logs_Call) RunAndReturn(run func(ctx context.Context, out io.Writer, name string, tail int) error) *MockWorkloadService_Logs_Call {
	_c.Call.Return(run)
	return _c
}
