// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api_test

import (
	"context"

	"github.com/dsb-labs/orca/internal/generated/api"
	"github.com/dsb-labs/orca/internal/server/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkloadService creates a new instance of MockWorkloadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkloadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkloadService {
	mock := &MockWorkloadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkloadService is an autogenerated mock type for the WorkloadService type
type MockWorkloadService struct {
	mock.Mock
}

type MockWorkloadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkloadService) EXPECT() *MockWorkloadService_Expecter {
	return &MockWorkloadService_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Apply(ctx context.Context, spec api.WorkloadSpec) (service.Workload, bool, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 service.Workload
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.WorkloadSpec) (service.Workload, bool, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.WorkloadSpec) service.Workload); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, api.WorkloadSpec) bool); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, api.WorkloadSpec) error); ok {
		r2 = returnFunc(ctx, spec)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWorkloadService_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockWorkloadService_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - spec api.WorkloadSpec
func (_e *MockWorkloadService_Expecter) Apply(ctx any, spec any) *MockWorkloadService_Apply_Call {
	return &MockWorkloadService_Apply_Call{Call: _e.mock.On("Apply", ctx, spec)}
}

func (_c *MockWorkloadService_Apply_Call) Run(run func(ctx context.Context, spec api.WorkloadSpec)) *MockWorkloadService_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 api.WorkloadSpec
		if args[1] != nil {
			arg1 = args[1].(api.WorkloadSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Apply_Call) Return(workload service.Workload, b bool, err error) *MockWorkloadService_Apply_Call {
	_c.Call.Return(workload, b, err)
	return _c
}

func (_c *MockWorkloadService_Apply_Call) RunAndReturn(run func(ctx context.Context, spec api.WorkloadSpec) (service.Workload, bool, error)) *MockWorkloadService_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkloadService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWorkloadService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadService_Expecter) Delete(ctx any, name any) *MockWorkloadService_Delete_Call {
	return &MockWorkloadService_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockWorkloadService_Delete_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Delete_Call) Return(err error) *MockWorkloadService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkloadService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockWorkloadService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Get(ctx context.Context, name string) (service.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkloadService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadService_Expecter) Get(ctx any, name any) *MockWorkloadService_Get_Call {
	return &MockWorkloadService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockWorkloadService_Get_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Get_Call) Return(workload service.Workload, err error) *MockWorkloadService_Get_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Workload, error)) *MockWorkloadService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) List(ctx context.Context) ([]service.Workload, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]service.Workload, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []service.Workload); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkloadService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWorkloadService_Expecter) List(ctx any) *MockWorkloadService_List_Call {
	return &MockWorkloadService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockWorkloadService_List_Call) Run(run func(ctx context.Context)) *MockWorkloadService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkloadService_List_Call) Return(workloads []service.Workload, err error) *MockWorkloadService_List_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *MockWorkloadService_List_Call) RunAndReturn(run func(ctx context.Context) ([]service.Workload, error)) *MockWorkloadService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Logs(ctx context.Context, name string, tail int) (string, error) {
	ret := _mock.Called(ctx, name, tail)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (string, error)); ok {
		return returnFunc(ctx, name, tail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) string); ok {
		r0 = returnFunc(ctx, name, tail)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, name, tail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type MockWorkloadService_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - tail int
func (_e *MockWorkloadService_Expecter) Logs(ctx any, name any, tail any) *MockWorkloadService_Logs_Call {
	return &MockWorkloadService_Logs_Call{Call: _e.mock.On("Logs", ctx, name, tail)}
}

func (_c *MockWorkloadService_Logs_Call) Run(run func(ctx context.Context, name string, tail int)) *MockWorkloadService_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Logs_Call) Return(s string, err error) *MockWorkloadService_Logs_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockWorkloadService_Logs_Call) RunAndReturn(run func(ctx context.Context, name string, tail int) (string, error)) *MockWorkloadService_Logs_Call {
	_c.Call.Return(run)
	return _c
}
