// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api_test

import (
	"context"
	"io"

	"github.com/dsb-labs/takt/internal/server/auth"
	"github.com/dsb-labs/takt/internal/server/driver"
	"github.com/dsb-labs/takt/internal/server/reconciler"
	"github.com/dsb-labs/takt/internal/server/service"
	"github.com/dsb-labs/takt/pkg/manifest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPolicyService creates a new instance of MockPolicyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicyService {
	mock := &MockPolicyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPolicyService is an autogenerated mock type for the PolicyService type
type MockPolicyService struct {
	mock.Mock
}

type MockPolicyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPolicyService) EXPECT() *MockPolicyService_Expecter {
	return &MockPolicyService_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockPolicyService
func (_mock *MockPolicyService) Apply(ctx context.Context, policy manifest.Policy, ifMatch string) (manifest.Policy, string, error) {
	ret := _mock.Called(ctx, policy, ifMatch)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 manifest.Policy
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Policy, string) (manifest.Policy, string, error)); ok {
		return returnFunc(ctx, policy, ifMatch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Policy, string) manifest.Policy); ok {
		r0 = returnFunc(ctx, policy, ifMatch)
	} else {
		r0 = ret.Get(0).(manifest.Policy)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifest.Policy, string) string); ok {
		r1 = returnFunc(ctx, policy, ifMatch)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, manifest.Policy, string) error); ok {
		r2 = returnFunc(ctx, policy, ifMatch)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPolicyService_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockPolicyService_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - policy manifest.Policy
//   - ifMatch string
func (_e *MockPolicyService_Expecter) Apply(ctx any, policy any, ifMatch any) *MockPolicyService_Apply_Call {
	return &MockPolicyService_Apply_Call{Call: _e.mock.On("Apply", ctx, policy, ifMatch)}
}

func (_c *MockPolicyService_Apply_Call) Run(run func(ctx context.Context, policy manifest.Policy, ifMatch string)) *MockPolicyService_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifest.Policy
		if args[1] != nil {
			arg1 = args[1].(manifest.Policy)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyService_Apply_Call) Return(policy1 manifest.Policy, s string, err error) *MockPolicyService_Apply_Call {
	_c.Call.Return(policy1, s, err)
	return _c
}

func (_c *MockPolicyService_Apply_Call) RunAndReturn(run func(ctx context.Context, policy manifest.Policy, ifMatch string) (manifest.Policy, string, error)) *MockPolicyService_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPolicyService
func (_mock *MockPolicyService) Get(ctx context.Context) (manifest.Policy, string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 manifest.Policy
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (manifest.Policy, string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) manifest.Policy); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(manifest.Policy)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPolicyService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPolicyService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPolicyService_Expecter) Get(ctx any) *MockPolicyService_Get_Call {
	return &MockPolicyService_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockPolicyService_Get_Call) Run(run func(ctx context.Context)) *MockPolicyService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPolicyService_Get_Call) Return(policy manifest.Policy, s string, err error) *MockPolicyService_Get_Call {
	_c.Call.Return(policy, s, err)
	return _c
}

func (_c *MockPolicyService_Get_Call) RunAndReturn(run func(ctx context.Context) (manifest.Policy, string, error)) *MockPolicyService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockACLInitializer creates a new instance of MockACLInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockACLInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockACLInitializer {
	mock := &MockACLInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockACLInitializer is an autogenerated mock type for the ACLInitializer type
type MockACLInitializer struct {
	mock.Mock
}

type MockACLInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockACLInitializer) EXPECT() *MockACLInitializer_Expecter {
	return &MockACLInitializer_Expecter{mock: &_m.Mock}
}

// Init provides a mock function for the type MockACLInitializer
func (_mock *MockACLInitializer) Init(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockACLInitializer_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockACLInitializer_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockACLInitializer_Expecter) Init(ctx any) *MockACLInitializer_Init_Call {
	return &MockACLInitializer_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockACLInitializer_Init_Call) Run(run func(ctx context.Context)) *MockACLInitializer_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockACLInitializer_Init_Call) Return(s string, err error) *MockACLInitializer_Init_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockACLInitializer_Init_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockACLInitializer_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdmin creates a new instance of MockAdmin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdmin(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdmin {
	mock := &MockAdmin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdmin is an autogenerated mock type for the Admin type
type MockAdmin struct {
	mock.Mock
}

type MockAdmin_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdmin) EXPECT() *MockAdmin_Expecter {
	return &MockAdmin_Expecter{mock: &_m.Mock}
}

// PrepareBackup provides a mock function for the type MockAdmin
func (_mock *MockAdmin) PrepareBackup(ctx context.Context, options service.BackupOptions) (*service.Backup, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for PrepareBackup")
	}

	var r0 *service.Backup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.BackupOptions) (*service.Backup, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.BackupOptions) *service.Backup); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Backup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, service.BackupOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdmin_PrepareBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareBackup'
type MockAdmin_PrepareBackup_Call struct {
	*mock.Call
}

// PrepareBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - options service.BackupOptions
func (_e *MockAdmin_Expecter) PrepareBackup(ctx any, options any) *MockAdmin_PrepareBackup_Call {
	return &MockAdmin_PrepareBackup_Call{Call: _e.mock.On("PrepareBackup", ctx, options)}
}

func (_c *MockAdmin_PrepareBackup_Call) Run(run func(ctx context.Context, options service.BackupOptions)) *MockAdmin_PrepareBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 service.BackupOptions
		if args[1] != nil {
			arg1 = args[1].(service.BackupOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_PrepareBackup_Call) Return(backup *service.Backup, err error) *MockAdmin_PrepareBackup_Call {
	_c.Call.Return(backup, err)
	return _c
}

func (_c *MockAdmin_PrepareBackup_Call) RunAndReturn(run func(ctx context.Context, options service.BackupOptions) (*service.Backup, error)) *MockAdmin_PrepareBackup_Call {
	_c.Call.Return(run)
	return _c
}

// Rekey provides a mock function for the type MockAdmin
func (_mock *MockAdmin) Rekey(ctx context.Context) (service.Rekey, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rekey")
	}

	var r0 service.Rekey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (service.Rekey, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) service.Rekey); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(service.Rekey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdmin_Rekey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rekey'
type MockAdmin_Rekey_Call struct {
	*mock.Call
}

// Rekey is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdmin_Expecter) Rekey(ctx any) *MockAdmin_Rekey_Call {
	return &MockAdmin_Rekey_Call{Call: _e.mock.On("Rekey", ctx)}
}

func (_c *MockAdmin_Rekey_Call) Run(run func(ctx context.Context)) *MockAdmin_Rekey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdmin_Rekey_Call) Return(rekey service.Rekey, err error) *MockAdmin_Rekey_Call {
	_c.Call.Return(rekey, err)
	return _c
}

func (_c *MockAdmin_Rekey_Call) RunAndReturn(run func(ctx context.Context) (service.Rekey, error)) *MockAdmin_Rekey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// LoginOIDC provides a mock function for the type MockAuthService
func (_mock *MockAuthService) LoginOIDC(ctx context.Context, rawIDToken string) (service.Token, string, error) {
	ret := _mock.Called(ctx, rawIDToken)

	if len(ret) == 0 {
		panic("no return value specified for LoginOIDC")
	}

	var r0 service.Token
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Token, string, error)); ok {
		return returnFunc(ctx, rawIDToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Token); ok {
		r0 = returnFunc(ctx, rawIDToken)
	} else {
		r0 = ret.Get(0).(service.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, rawIDToken)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, rawIDToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_LoginOIDC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginOIDC'
type MockAuthService_LoginOIDC_Call struct {
	*mock.Call
}

// LoginOIDC is a helper method to define mock.On call
//   - ctx context.Context
//   - rawIDToken string
func (_e *MockAuthService_Expecter) LoginOIDC(ctx any, rawIDToken any) *MockAuthService_LoginOIDC_Call {
	return &MockAuthService_LoginOIDC_Call{Call: _e.mock.On("LoginOIDC", ctx, rawIDToken)}
}

func (_c *MockAuthService_LoginOIDC_Call) Run(run func(ctx context.Context, rawIDToken string)) *MockAuthService_LoginOIDC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_LoginOIDC_Call) Return(token service.Token, s string, err error) *MockAuthService_LoginOIDC_Call {
	_c.Call.Return(token, s, err)
	return _c
}

func (_c *MockAuthService_LoginOIDC_Call) RunAndReturn(run func(ctx context.Context, rawIDToken string) (service.Token, string, error)) *MockAuthService_LoginOIDC_Call {
	_c.Call.Return(run)
	return _c
}

// LoginToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) LoginToken(ctx context.Context, credential string) (service.Token, string, error) {
	ret := _mock.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for LoginToken")
	}

	var r0 service.Token
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Token, string, error)); ok {
		return returnFunc(ctx, credential)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Token); ok {
		r0 = returnFunc(ctx, credential)
	} else {
		r0 = ret.Get(0).(service.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, credential)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, credential)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_LoginToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginToken'
type MockAuthService_LoginToken_Call struct {
	*mock.Call
}

// LoginToken is a helper method to define mock.On call
//   - ctx context.Context
//   - credential string
func (_e *MockAuthService_Expecter) LoginToken(ctx any, credential any) *MockAuthService_LoginToken_Call {
	return &MockAuthService_LoginToken_Call{Call: _e.mock.On("LoginToken", ctx, credential)}
}

func (_c *MockAuthService_LoginToken_Call) Run(run func(ctx context.Context, credential string)) *MockAuthService_LoginToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_LoginToken_Call) Return(token service.Token, s string, err error) *MockAuthService_LoginToken_Call {
	_c.Call.Return(token, s, err)
	return _c
}

func (_c *MockAuthService_LoginToken_Call) RunAndReturn(run func(ctx context.Context, credential string) (service.Token, string, error)) *MockAuthService_LoginToken_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(ctx context.Context, identity auth.Identity) error {
	ret := _mock.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Identity) error); ok {
		r0 = returnFunc(ctx, identity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - identity auth.Identity
func (_e *MockAuthService_Expecter) Logout(ctx any, identity any) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, identity)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, identity auth.Identity)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.Identity
		if args[1] != nil {
			arg1 = args[1].(auth.Identity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, identity auth.Identity) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretService creates a new instance of MockSecretService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretService {
	mock := &MockSecretService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretService is an autogenerated mock type for the SecretService type
type MockSecretService struct {
	mock.Mock
}

type MockSecretService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretService) EXPECT() *MockSecretService_Expecter {
	return &MockSecretService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSecretService
func (_mock *MockSecretService) Delete(ctx context.Context, name string, force bool) error {
	ret := _mock.Called(ctx, name, force)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, name, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - force bool
func (_e *MockSecretService_Expecter) Delete(ctx any, name any, force any) *MockSecretService_Delete_Call {
	return &MockSecretService_Delete_Call{Call: _e.mock.On("Delete", ctx, name, force)}
}

func (_c *MockSecretService_Delete_Call) Run(run func(ctx context.Context, name string, force bool)) *MockSecretService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretService_Delete_Call) Return(err error) *MockSecretService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, force bool) error) *MockSecretService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSecretService
func (_mock *MockSecretService) Get(ctx context.Context, name string) (service.Secret, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Secret, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Secret); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSecretService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSecretService_Expecter) Get(ctx any, name any) *MockSecretService_Get_Call {
	return &MockSecretService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockSecretService_Get_Call) Run(run func(ctx context.Context, name string)) *MockSecretService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretService_Get_Call) Return(secret service.Secret, err error) *MockSecretService_Get_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Secret, error)) *MockSecretService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSecretService
func (_mock *MockSecretService) List(ctx context.Context, queries ...string) ([]service.Secret, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]service.Secret, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []service.Secret); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSecretService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockSecretService_Expecter) List(ctx any, queries ...any) *MockSecretService_List_Call {
	return &MockSecretService_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockSecretService_List_Call) Run(run func(ctx context.Context, queries ...string)) *MockSecretService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockSecretService_List_Call) Return(secrets []service.Secret, err error) *MockSecretService_List_Call {
	_c.Call.Return(secrets, err)
	return _c
}

func (_c *MockSecretService_List_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]service.Secret, error)) *MockSecretService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockSecretService
func (_mock *MockSecretService) Set(ctx context.Context, name string, value []byte, labels map[string]string) (service.Secret, bool, error) {
	ret := _mock.Called(ctx, name, value, labels)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 service.Secret
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, map[string]string) (service.Secret, bool, error)); ok {
		return returnFunc(ctx, name, value, labels)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, map[string]string) service.Secret); ok {
		r0 = returnFunc(ctx, name, value, labels)
	} else {
		r0 = ret.Get(0).(service.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, map[string]string) bool); ok {
		r1 = returnFunc(ctx, name, value, labels)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []byte, map[string]string) error); ok {
		r2 = returnFunc(ctx, name, value, labels)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSecretService_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSecretService_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value []byte
//   - labels map[string]string
func (_e *MockSecretService_Expecter) Set(ctx any, name any, value any, labels any) *MockSecretService_Set_Call {
	return &MockSecretService_Set_Call{Call: _e.mock.On("Set", ctx, name, value, labels)}
}

func (_c *MockSecretService_Set_Call) Run(run func(ctx context.Context, name string, value []byte, labels map[string]string)) *MockSecretService_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSecretService_Set_Call) Return(secret service.Secret, b bool, err error) *MockSecretService_Set_Call {
	_c.Call.Return(secret, b, err)
	return _c
}

func (_c *MockSecretService_Set_Call) RunAndReturn(run func(ctx context.Context, name string, value []byte, labels map[string]string) (service.Secret, bool, error)) *MockSecretService_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceService creates a new instance of MockServiceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceService {
	mock := &MockServiceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceService is an autogenerated mock type for the ServiceService type
type MockServiceService struct {
	mock.Mock
}

type MockServiceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceService) EXPECT() *MockServiceService_Expecter {
	return &MockServiceService_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockServiceService
func (_mock *MockServiceService) Apply(ctx context.Context, spec manifest.Service) (service.Service, bool, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 service.Service
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Service) (service.Service, bool, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Service) service.Service); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(service.Service)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifest.Service) bool); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, manifest.Service) error); ok {
		r2 = returnFunc(ctx, spec)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockServiceService_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockServiceService_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - spec manifest.Service
func (_e *MockServiceService_Expecter) Apply(ctx any, spec any) *MockServiceService_Apply_Call {
	return &MockServiceService_Apply_Call{Call: _e.mock.On("Apply", ctx, spec)}
}

func (_c *MockServiceService_Apply_Call) Run(run func(ctx context.Context, spec manifest.Service)) *MockServiceService_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifest.Service
		if args[1] != nil {
			arg1 = args[1].(manifest.Service)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceService_Apply_Call) Return(service1 service.Service, b bool, err error) *MockServiceService_Apply_Call {
	_c.Call.Return(service1, b, err)
	return _c
}

func (_c *MockServiceService_Apply_Call) RunAndReturn(run func(ctx context.Context, spec manifest.Service) (service.Service, bool, error)) *MockServiceService_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockServiceService
func (_mock *MockServiceService) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServiceService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockServiceService_Expecter) Delete(ctx any, name any) *MockServiceService_Delete_Call {
	return &MockServiceService_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockServiceService_Delete_Call) Run(run func(ctx context.Context, name string)) *MockServiceService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceService_Delete_Call) Return(err error) *MockServiceService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockServiceService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockServiceService
func (_mock *MockServiceService) Get(ctx context.Context, name string) (service.Service, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Service, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Service); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Service)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockServiceService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockServiceService_Expecter) Get(ctx any, name any) *MockServiceService_Get_Call {
	return &MockServiceService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockServiceService_Get_Call) Run(run func(ctx context.Context, name string)) *MockServiceService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceService_Get_Call) Return(service1 service.Service, err error) *MockServiceService_Get_Call {
	_c.Call.Return(service1, err)
	return _c
}

func (_c *MockServiceService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Service, error)) *MockServiceService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockServiceService
func (_mock *MockServiceService) List(ctx context.Context, queries ...string) ([]service.Service, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]service.Service, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []service.Service); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServiceService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockServiceService_Expecter) List(ctx any, queries ...any) *MockServiceService_List_Call {
	return &MockServiceService_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockServiceService_List_Call) Run(run func(ctx context.Context, queries ...string)) *MockServiceService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockServiceService_List_Call) Return(services []service.Service, err error) *MockServiceService_List_Call {
	_c.Call.Return(services, err)
	return _c
}

func (_c *MockServiceService_List_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]service.Service, error)) *MockServiceService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPinger creates a new instance of MockPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinger {
	mock := &MockPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPinger is an autogenerated mock type for the Pinger type
type MockPinger struct {
	mock.Mock
}

type MockPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinger) EXPECT() *MockPinger_Expecter {
	return &MockPinger_Expecter{mock: &_m.Mock}
}

// PingContext provides a mock function for the type MockPinger
func (_mock *MockPinger) PingContext(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPinger_PingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingContext'
type MockPinger_PingContext_Call struct {
	*mock.Call
}

// PingContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPinger_Expecter) PingContext(ctx any) *MockPinger_PingContext_Call {
	return &MockPinger_PingContext_Call{Call: _e.mock.On("PingContext", ctx)}
}

func (_c *MockPinger_PingContext_Call) Run(run func(ctx context.Context)) *MockPinger_PingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPinger_PingContext_Call) Return(err error) *MockPinger_PingContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPinger_PingContext_Call) RunAndReturn(run func(ctx context.Context) error) *MockPinger_PingContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObserver creates a new instance of MockObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObserver {
	mock := &MockObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObserver is an autogenerated mock type for the Observer type
type MockObserver struct {
	mock.Mock
}

type MockObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObserver) EXPECT() *MockObserver_Expecter {
	return &MockObserver_Expecter{mock: &_m.Mock}
}

// Observations provides a mock function for the type MockObserver
func (_mock *MockObserver) Observations() map[string]reconciler.Observation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Observations")
	}

	var r0 map[string]reconciler.Observation
	if returnFunc, ok := ret.Get(0).(func() map[string]reconciler.Observation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]reconciler.Observation)
		}
	}
	return r0
}

// MockObserver_Observations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observations'
type MockObserver_Observations_Call struct {
	*mock.Call
}

// Observations is a helper method to define mock.On call
func (_e *MockObserver_Expecter) Observations() *MockObserver_Observations_Call {
	return &MockObserver_Observations_Call{Call: _e.mock.On("Observations")}
}

func (_c *MockObserver_Observations_Call) Run(run func()) *MockObserver_Observations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObserver_Observations_Call) Return(stringToObservation map[string]reconciler.Observation) *MockObserver_Observations_Call {
	_c.Call.Return(stringToObservation)
	return _c
}

func (_c *MockObserver_Observations_Call) RunAndReturn(run func() map[string]reconciler.Observation) *MockObserver_Observations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScrapeTargeter creates a new instance of MockScrapeTargeter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScrapeTargeter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScrapeTargeter {
	mock := &MockScrapeTargeter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScrapeTargeter is an autogenerated mock type for the ScrapeTargeter type
type MockScrapeTargeter struct {
	mock.Mock
}

type MockScrapeTargeter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScrapeTargeter) EXPECT() *MockScrapeTargeter_Expecter {
	return &MockScrapeTargeter_Expecter{mock: &_m.Mock}
}

// ScrapeTargets provides a mock function for the type MockScrapeTargeter
func (_mock *MockScrapeTargeter) ScrapeTargets(ctx context.Context) ([]service.ScrapeTarget, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ScrapeTargets")
	}

	var r0 []service.ScrapeTarget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]service.ScrapeTarget, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []service.ScrapeTarget); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.ScrapeTarget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScrapeTargeter_ScrapeTargets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScrapeTargets'
type MockScrapeTargeter_ScrapeTargets_Call struct {
	*mock.Call
}

// ScrapeTargets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockScrapeTargeter_Expecter) ScrapeTargets(ctx any) *MockScrapeTargeter_ScrapeTargets_Call {
	return &MockScrapeTargeter_ScrapeTargets_Call{Call: _e.mock.On("ScrapeTargets", ctx)}
}

func (_c *MockScrapeTargeter_ScrapeTargets_Call) Run(run func(ctx context.Context)) *MockScrapeTargeter_ScrapeTargets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScrapeTargeter_ScrapeTargets_Call) Return(scrapeTargets []service.ScrapeTarget, err error) *MockScrapeTargeter_ScrapeTargets_Call {
	_c.Call.Return(scrapeTargets, err)
	return _c
}

func (_c *MockScrapeTargeter_ScrapeTargets_Call) RunAndReturn(run func(ctx context.Context) ([]service.ScrapeTarget, error)) *MockScrapeTargeter_ScrapeTargets_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Create(ctx context.Context, principal string) (service.Token, string, error) {
	ret := _mock.Called(ctx, principal)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 service.Token
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Token, string, error)); ok {
		return returnFunc(ctx, principal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Token); ok {
		r0 = returnFunc(ctx, principal)
	} else {
		r0 = ret.Get(0).(service.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, principal)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, principal)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - principal string
func (_e *MockTokenService_Expecter) Create(ctx any, principal any) *MockTokenService_Create_Call {
	return &MockTokenService_Create_Call{Call: _e.mock.On("Create", ctx, principal)}
}

func (_c *MockTokenService_Create_Call) Run(run func(ctx context.Context, principal string)) *MockTokenService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_Create_Call) Return(token service.Token, s string, err error) *MockTokenService_Create_Call {
	_c.Call.Return(token, s, err)
	return _c
}

func (_c *MockTokenService_Create_Call) RunAndReturn(run func(ctx context.Context, principal string) (service.Token, string, error)) *MockTokenService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTokenService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTokenService_Expecter) Delete(ctx any, id any) *MockTokenService_Delete_Call {
	return &MockTokenService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTokenService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockTokenService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_Delete_Call) Return(err error) *MockTokenService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockTokenService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTokenService
func (_mock *MockTokenService) List(ctx context.Context) ([]service.Token, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]service.Token, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []service.Token); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTokenService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTokenService_Expecter) List(ctx any) *MockTokenService_List_Call {
	return &MockTokenService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTokenService_List_Call) Run(run func(ctx context.Context)) *MockTokenService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_List_Call) Return(tokens []service.Token, err error) *MockTokenService_List_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *MockTokenService_List_Call) RunAndReturn(run func(ctx context.Context) ([]service.Token, error)) *MockTokenService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVariableService creates a new instance of MockVariableService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVariableService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVariableService {
	mock := &MockVariableService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVariableService is an autogenerated mock type for the VariableService type
type MockVariableService struct {
	mock.Mock
}

type MockVariableService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVariableService) EXPECT() *MockVariableService_Expecter {
	return &MockVariableService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockVariableService
func (_mock *MockVariableService) Delete(ctx context.Context, name string, force bool) error {
	ret := _mock.Called(ctx, name, force)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, name, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVariableService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVariableService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - force bool
func (_e *MockVariableService_Expecter) Delete(ctx any, name any, force any) *MockVariableService_Delete_Call {
	return &MockVariableService_Delete_Call{Call: _e.mock.On("Delete", ctx, name, force)}
}

func (_c *MockVariableService_Delete_Call) Run(run func(ctx context.Context, name string, force bool)) *MockVariableService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVariableService_Delete_Call) Return(err error) *MockVariableService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVariableService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, force bool) error) *MockVariableService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockVariableService
func (_mock *MockVariableService) Get(ctx context.Context, name string) (service.Variable, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Variable
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Variable, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Variable); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Variable)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVariableService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVariableService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockVariableService_Expecter) Get(ctx any, name any) *MockVariableService_Get_Call {
	return &MockVariableService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockVariableService_Get_Call) Run(run func(ctx context.Context, name string)) *MockVariableService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVariableService_Get_Call) Return(variable service.Variable, err error) *MockVariableService_Get_Call {
	_c.Call.Return(variable, err)
	return _c
}

func (_c *MockVariableService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Variable, error)) *MockVariableService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVariableService
func (_mock *MockVariableService) List(ctx context.Context, queries ...string) ([]service.Variable, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Variable
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]service.Variable, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []service.Variable); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Variable)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVariableService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVariableService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockVariableService_Expecter) List(ctx any, queries ...any) *MockVariableService_List_Call {
	return &MockVariableService_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockVariableService_List_Call) Run(run func(ctx context.Context, queries ...string)) *MockVariableService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockVariableService_List_Call) Return(variables []service.Variable, err error) *MockVariableService_List_Call {
	_c.Call.Return(variables, err)
	return _c
}

func (_c *MockVariableService_List_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]service.Variable, error)) *MockVariableService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockVariableService
func (_mock *MockVariableService) Set(ctx context.Context, name string, value string, labels map[string]string) (service.Variable, bool, error) {
	ret := _mock.Called(ctx, name, value, labels)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 service.Variable
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) (service.Variable, bool, error)); ok {
		return returnFunc(ctx, name, value, labels)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) service.Variable); ok {
		r0 = returnFunc(ctx, name, value, labels)
	} else {
		r0 = ret.Get(0).(service.Variable)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, map[string]string) bool); ok {
		r1 = returnFunc(ctx, name, value, labels)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, map[string]string) error); ok {
		r2 = returnFunc(ctx, name, value, labels)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockVariableService_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockVariableService_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value string
//   - labels map[string]string
func (_e *MockVariableService_Expecter) Set(ctx any, name any, value any, labels any) *MockVariableService_Set_Call {
	return &MockVariableService_Set_Call{Call: _e.mock.On("Set", ctx, name, value, labels)}
}

func (_c *MockVariableService_Set_Call) Run(run func(ctx context.Context, name string, value string, labels map[string]string)) *MockVariableService_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVariableService_Set_Call) Return(variable service.Variable, b bool, err error) *MockVariableService_Set_Call {
	_c.Call.Return(variable, b, err)
	return _c
}

func (_c *MockVariableService_Set_Call) RunAndReturn(run func(ctx context.Context, name string, value string, labels map[string]string) (service.Variable, bool, error)) *MockVariableService_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVolumeService creates a new instance of MockVolumeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeService {
	mock := &MockVolumeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVolumeService is an autogenerated mock type for the VolumeService type
type MockVolumeService struct {
	mock.Mock
}

type MockVolumeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeService) EXPECT() *MockVolumeService_Expecter {
	return &MockVolumeService_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) Apply(ctx context.Context, volume manifest.Volume) (service.Volume, bool, error) {
	ret := _mock.Called(ctx, volume)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 service.Volume
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Volume) (service.Volume, bool, error)); ok {
		return returnFunc(ctx, volume)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Volume) service.Volume); ok {
		r0 = returnFunc(ctx, volume)
	} else {
		r0 = ret.Get(0).(service.Volume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifest.Volume) bool); ok {
		r1 = returnFunc(ctx, volume)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, manifest.Volume) error); ok {
		r2 = returnFunc(ctx, volume)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockVolumeService_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockVolumeService_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - volume manifest.Volume
func (_e *MockVolumeService_Expecter) Apply(ctx any, volume any) *MockVolumeService_Apply_Call {
	return &MockVolumeService_Apply_Call{Call: _e.mock.On("Apply", ctx, volume)}
}

func (_c *MockVolumeService_Apply_Call) Run(run func(ctx context.Context, volume manifest.Volume)) *MockVolumeService_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifest.Volume
		if args[1] != nil {
			arg1 = args[1].(manifest.Volume)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVolumeService_Apply_Call) Return(volume1 service.Volume, b bool, err error) *MockVolumeService_Apply_Call {
	_c.Call.Return(volume1, b, err)
	return _c
}

func (_c *MockVolumeService_Apply_Call) RunAndReturn(run func(ctx context.Context, volume manifest.Volume) (service.Volume, bool, error)) *MockVolumeService_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) Delete(ctx context.Context, name string, force bool) error {
	ret := _mock.Called(ctx, name, force)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, name, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVolumeService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVolumeService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - force bool
func (_e *MockVolumeService_Expecter) Delete(ctx any, name any, force any) *MockVolumeService_Delete_Call {
	return &MockVolumeService_Delete_Call{Call: _e.mock.On("Delete", ctx, name, force)}
}

func (_c *MockVolumeService_Delete_Call) Run(run func(ctx context.Context, name string, force bool)) *MockVolumeService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVolumeService_Delete_Call) Return(err error) *MockVolumeService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVolumeService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, force bool) error) *MockVolumeService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) Get(ctx context.Context, name string) (service.Volume, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Volume, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Volume); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Volume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVolumeService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockVolumeService_Expecter) Get(ctx any, name any) *MockVolumeService_Get_Call {
	return &MockVolumeService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockVolumeService_Get_Call) Run(run func(ctx context.Context, name string)) *MockVolumeService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVolumeService_Get_Call) Return(volume service.Volume, err error) *MockVolumeService_Get_Call {
	_c.Call.Return(volume, err)
	return _c
}

func (_c *MockVolumeService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Volume, error)) *MockVolumeService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) List(ctx context.Context, queries ...string) ([]service.Volume, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]service.Volume, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []service.Volume); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVolumeService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockVolumeService_Expecter) List(ctx any, queries ...any) *MockVolumeService_List_Call {
	return &MockVolumeService_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockVolumeService_List_Call) Run(run func(ctx context.Context, queries ...string)) *MockVolumeService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockVolumeService_List_Call) Return(volumes []service.Volume, err error) *MockVolumeService_List_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *MockVolumeService_List_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]service.Volume, error)) *MockVolumeService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkloadService creates a new instance of MockWorkloadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkloadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkloadService {
	mock := &MockWorkloadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkloadService is an autogenerated mock type for the WorkloadService type
type MockWorkloadService struct {
	mock.Mock
}

type MockWorkloadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkloadService) EXPECT() *MockWorkloadService_Expecter {
	return &MockWorkloadService_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Apply(ctx context.Context, spec manifest.Spec) (service.Workload, bool, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 service.Workload
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Spec) (service.Workload, bool, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Spec) service.Workload); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifest.Spec) bool); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, manifest.Spec) error); ok {
		r2 = returnFunc(ctx, spec)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWorkloadService_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockWorkloadService_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - spec manifest.Spec
func (_e *MockWorkloadService_Expecter) Apply(ctx any, spec any) *MockWorkloadService_Apply_Call {
	return &MockWorkloadService_Apply_Call{Call: _e.mock.On("Apply", ctx, spec)}
}

func (_c *MockWorkloadService_Apply_Call) Run(run func(ctx context.Context, spec manifest.Spec)) *MockWorkloadService_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifest.Spec
		if args[1] != nil {
			arg1 = args[1].(manifest.Spec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Apply_Call) Return(workload service.Workload, b bool, err error) *MockWorkloadService_Apply_Call {
	_c.Call.Return(workload, b, err)
	return _c
}

func (_c *MockWorkloadService_Apply_Call) RunAndReturn(run func(ctx context.Context, spec manifest.Spec) (service.Workload, bool, error)) *MockWorkloadService_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Delete(ctx context.Context, name string, force bool) (service.Workload, error) {
	ret := _mock.Called(ctx, name, force)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (service.Workload, error)); ok {
		return returnFunc(ctx, name, force)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) service.Workload); ok {
		r0 = returnFunc(ctx, name, force)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, name, force)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWorkloadService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - force bool
func (_e *MockWorkloadService_Expecter) Delete(ctx any, name any, force any) *MockWorkloadService_Delete_Call {
	return &MockWorkloadService_Delete_Call{Call: _e.mock.On("Delete", ctx, name, force)}
}

func (_c *MockWorkloadService_Delete_Call) Run(run func(ctx context.Context, name string, force bool)) *MockWorkloadService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Delete_Call) Return(workload service.Workload, err error) *MockWorkloadService_Delete_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, force bool) (service.Workload, error)) *MockWorkloadService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DryRun provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) DryRun(ctx context.Context, spec manifest.Spec) (service.DryRun, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for DryRun")
	}

	var r0 service.DryRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Spec) (service.DryRun, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Spec) service.DryRun); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(service.DryRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifest.Spec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_DryRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DryRun'
type MockWorkloadService_DryRun_Call struct {
	*mock.Call
}

// DryRun is a helper method to define mock.On call
//   - ctx context.Context
//   - spec manifest.Spec
func (_e *MockWorkloadService_Expecter) DryRun(ctx any, spec any) *MockWorkloadService_DryRun_Call {
	return &MockWorkloadService_DryRun_Call{Call: _e.mock.On("DryRun", ctx, spec)}
}

func (_c *MockWorkloadService_DryRun_Call) Run(run func(ctx context.Context, spec manifest.Spec)) *MockWorkloadService_DryRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifest.Spec
		if args[1] != nil {
			arg1 = args[1].(manifest.Spec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_DryRun_Call) Return(dryRun service.DryRun, err error) *MockWorkloadService_DryRun_Call {
	_c.Call.Return(dryRun, err)
	return _c
}

func (_c *MockWorkloadService_DryRun_Call) RunAndReturn(run func(ctx context.Context, spec manifest.Spec) (service.DryRun, error)) *MockWorkloadService_DryRun_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Get(ctx context.Context, name string) (service.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkloadService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadService_Expecter) Get(ctx any, name any) *MockWorkloadService_Get_Call {
	return &MockWorkloadService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockWorkloadService_Get_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Get_Call) Return(workload service.Workload, err error) *MockWorkloadService_Get_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Workload, error)) *MockWorkloadService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) List(ctx context.Context, queries ...string) ([]service.Workload, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]service.Workload, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []service.Workload); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkloadService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockWorkloadService_Expecter) List(ctx any, queries ...any) *MockWorkloadService_List_Call {
	return &MockWorkloadService_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockWorkloadService_List_Call) Run(run func(ctx context.Context, queries ...string)) *MockWorkloadService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWorkloadService_List_Call) Return(workloads []service.Workload, err error) *MockWorkloadService_List_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *MockWorkloadService_List_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]service.Workload, error)) *MockWorkloadService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Logs(ctx context.Context, out io.Writer, name string, options driver.LogOptions) error {
	ret := _mock.Called(ctx, out, name, options)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Writer, string, driver.LogOptions) error); ok {
		r0 = returnFunc(ctx, out, name, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkloadService_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type MockWorkloadService_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - out io.Writer
//   - name string
//   - options driver.LogOptions
func (_e *MockWorkloadService_Expecter) Logs(ctx any, out any, name any, options any) *MockWorkloadService_Logs_Call {
	return &MockWorkloadService_Logs_Call{Call: _e.mock.On("Logs", ctx, out, name, options)}
}

func (_c *MockWorkloadService_Logs_Call) Run(run func(ctx context.Context, out io.Writer, name string, options driver.LogOptions)) *MockWorkloadService_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 driver.LogOptions
		if args[3] != nil {
			arg3 = args[3].(driver.LogOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Logs_Call) Return(err error) *MockWorkloadService_Logs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkloadService_Logs_Call) RunAndReturn(run func(ctx context.Context, out io.Writer, name string, options driver.LogOptions) error) *MockWorkloadService_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Restart provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Restart(ctx context.Context, name string) (service.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type MockWorkloadService_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadService_Expecter) Restart(ctx any, name any) *MockWorkloadService_Restart_Call {
	return &MockWorkloadService_Restart_Call{Call: _e.mock.On("Restart", ctx, name)}
}

func (_c *MockWorkloadService_Restart_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadService_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Restart_Call) Return(workload service.Workload, err error) *MockWorkloadService_Restart_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadService_Restart_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Workload, error)) *MockWorkloadService_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Start(ctx context.Context, name string) (service.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWorkloadService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadService_Expecter) Start(ctx any, name any) *MockWorkloadService_Start_Call {
	return &MockWorkloadService_Start_Call{Call: _e.mock.On("Start", ctx, name)}
}

func (_c *MockWorkloadService_Start_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Start_Call) Return(workload service.Workload, err error) *MockWorkloadService_Start_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadService_Start_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Workload, error)) *MockWorkloadService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockWorkloadService
func (_mock *MockWorkloadService) Stop(ctx context.Context, name string) (service.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 service.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(service.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkloadService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockWorkloadService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkloadService_Expecter) Stop(ctx any, name any) *MockWorkloadService_Stop_Call {
	return &MockWorkloadService_Stop_Call{Call: _e.mock.On("Stop", ctx, name)}
}

func (_c *MockWorkloadService_Stop_Call) Run(run func(ctx context.Context, name string)) *MockWorkloadService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkloadService_Stop_Call) Return(workload service.Workload, err error) *MockWorkloadService_Stop_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockWorkloadService_Stop_Call) RunAndReturn(run func(ctx context.Context, name string) (service.Workload, error)) *MockWorkloadService_Stop_Call {
	_c.Call.Return(run)
	return _c
}
