// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package score_test

import (
	"context"

	"github.com/dsb-labs/takt/pkg/client"
	"github.com/dsb-labs/takt/pkg/manifest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockClient
func (_mock *MockClient) Apply(ctx context.Context, spec manifest.Spec, options ...client.ApplyOption) (client.Workload, bool, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, spec, options)
	} else {
		tmpRet = _mock.Called(ctx, spec)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 client.Workload
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Spec, ...client.ApplyOption) (client.Workload, bool, error)); ok {
		return returnFunc(ctx, spec, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Spec, ...client.ApplyOption) client.Workload); ok {
		r0 = returnFunc(ctx, spec, options...)
	} else {
		r0 = ret.Get(0).(client.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifest.Spec, ...client.ApplyOption) bool); ok {
		r1 = returnFunc(ctx, spec, options...)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, manifest.Spec, ...client.ApplyOption) error); ok {
		r2 = returnFunc(ctx, spec, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockClient_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - spec manifest.Spec
//   - options ...client.ApplyOption
func (_e *MockClient_Expecter) Apply(ctx any, spec any, options ...any) *MockClient_Apply_Call {
	return &MockClient_Apply_Call{Call: _e.mock.On("Apply",
		append([]any{ctx, spec}, options...)...)}
}

func (_c *MockClient_Apply_Call) Run(run func(ctx context.Context, spec manifest.Spec, options ...client.ApplyOption)) *MockClient_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifest.Spec
		if args[1] != nil {
			arg1 = args[1].(manifest.Spec)
		}
		var arg2 []client.ApplyOption
		var variadicArgs []client.ApplyOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.ApplyOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_Apply_Call) Return(workload client.Workload, b bool, err error) *MockClient_Apply_Call {
	_c.Call.Return(workload, b, err)
	return _c
}

func (_c *MockClient_Apply_Call) RunAndReturn(run func(ctx context.Context, spec manifest.Spec, options ...client.ApplyOption) (client.Workload, bool, error)) *MockClient_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyService provides a mock function for the type MockClient
func (_mock *MockClient) ApplyService(ctx context.Context, service manifest.Service, options ...client.ApplyOption) (client.Service, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, service, options)
	} else {
		tmpRet = _mock.Called(ctx, service)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ApplyService")
	}

	var r0 client.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Service, ...client.ApplyOption) (client.Service, error)); ok {
		return returnFunc(ctx, service, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Service, ...client.ApplyOption) client.Service); ok {
		r0 = returnFunc(ctx, service, options...)
	} else {
		r0 = ret.Get(0).(client.Service)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifest.Service, ...client.ApplyOption) error); ok {
		r1 = returnFunc(ctx, service, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ApplyService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyService'
type MockClient_ApplyService_Call struct {
	*mock.Call
}

// ApplyService is a helper method to define mock.On call
//   - ctx context.Context
//   - service manifest.Service
//   - options ...client.ApplyOption
func (_e *MockClient_Expecter) ApplyService(ctx any, service any, options ...any) *MockClient_ApplyService_Call {
	return &MockClient_ApplyService_Call{Call: _e.mock.On("ApplyService",
		append([]any{ctx, service}, options...)...)}
}

func (_c *MockClient_ApplyService_Call) Run(run func(ctx context.Context, service manifest.Service, options ...client.ApplyOption)) *MockClient_ApplyService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifest.Service
		if args[1] != nil {
			arg1 = args[1].(manifest.Service)
		}
		var arg2 []client.ApplyOption
		var variadicArgs []client.ApplyOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.ApplyOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ApplyService_Call) Return(service1 client.Service, err error) *MockClient_ApplyService_Call {
	_c.Call.Return(service1, err)
	return _c
}

func (_c *MockClient_ApplyService_Call) RunAndReturn(run func(ctx context.Context, service manifest.Service, options ...client.ApplyOption) (client.Service, error)) *MockClient_ApplyService_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyVolume provides a mock function for the type MockClient
func (_mock *MockClient) ApplyVolume(ctx context.Context, volume manifest.Volume, options ...client.ApplyOption) (client.Volume, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, volume, options)
	} else {
		tmpRet = _mock.Called(ctx, volume)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ApplyVolume")
	}

	var r0 client.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Volume, ...client.ApplyOption) (client.Volume, error)); ok {
		return returnFunc(ctx, volume, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Volume, ...client.ApplyOption) client.Volume); ok {
		r0 = returnFunc(ctx, volume, options...)
	} else {
		r0 = ret.Get(0).(client.Volume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifest.Volume, ...client.ApplyOption) error); ok {
		r1 = returnFunc(ctx, volume, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ApplyVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyVolume'
type MockClient_ApplyVolume_Call struct {
	*mock.Call
}

// ApplyVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - volume manifest.Volume
//   - options ...client.ApplyOption
func (_e *MockClient_Expecter) ApplyVolume(ctx any, volume any, options ...any) *MockClient_ApplyVolume_Call {
	return &MockClient_ApplyVolume_Call{Call: _e.mock.On("ApplyVolume",
		append([]any{ctx, volume}, options...)...)}
}

func (_c *MockClient_ApplyVolume_Call) Run(run func(ctx context.Context, volume manifest.Volume, options ...client.ApplyOption)) *MockClient_ApplyVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifest.Volume
		if args[1] != nil {
			arg1 = args[1].(manifest.Volume)
		}
		var arg2 []client.ApplyOption
		var variadicArgs []client.ApplyOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.ApplyOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ApplyVolume_Call) Return(volume1 client.Volume, err error) *MockClient_ApplyVolume_Call {
	_c.Call.Return(volume1, err)
	return _c
}

func (_c *MockClient_ApplyVolume_Call) RunAndReturn(run func(ctx context.Context, volume manifest.Volume, options ...client.ApplyOption) (client.Volume, error)) *MockClient_ApplyVolume_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockClient
func (_mock *MockClient) Delete(ctx context.Context, name string, options ...client.LifecycleOption) (client.Workload, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, name, options)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 client.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.LifecycleOption) (client.Workload, error)); ok {
		return returnFunc(ctx, name, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.LifecycleOption) client.Workload); ok {
		r0 = returnFunc(ctx, name, options...)
	} else {
		r0 = ret.Get(0).(client.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.LifecycleOption) error); ok {
		r1 = returnFunc(ctx, name, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options ...client.LifecycleOption
func (_e *MockClient_Expecter) Delete(ctx any, name any, options ...any) *MockClient_Delete_Call {
	return &MockClient_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, name}, options...)...)}
}

func (_c *MockClient_Delete_Call) Run(run func(ctx context.Context, name string, options ...client.LifecycleOption)) *MockClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.LifecycleOption
		var variadicArgs []client.LifecycleOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.LifecycleOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_Delete_Call) Return(workload client.Workload, err error) *MockClient_Delete_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockClient_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, options ...client.LifecycleOption) (client.Workload, error)) *MockClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteService provides a mock function for the type MockClient
func (_mock *MockClient) DeleteService(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteService")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteService'
type MockClient_DeleteService_Call struct {
	*mock.Call
}

// DeleteService is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClient_Expecter) DeleteService(ctx any, name any) *MockClient_DeleteService_Call {
	return &MockClient_DeleteService_Call{Call: _e.mock.On("DeleteService", ctx, name)}
}

func (_c *MockClient_DeleteService_Call) Run(run func(ctx context.Context, name string)) *MockClient_DeleteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_DeleteService_Call) Return(err error) *MockClient_DeleteService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteService_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockClient_DeleteService_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVariable provides a mock function for the type MockClient
func (_mock *MockClient) DeleteVariable(ctx context.Context, name string, options ...client.DeleteVariableOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, name, options)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteVariable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.DeleteVariableOption) error); ok {
		r0 = returnFunc(ctx, name, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVariable'
type MockClient_DeleteVariable_Call struct {
	*mock.Call
}

// DeleteVariable is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options ...client.DeleteVariableOption
func (_e *MockClient_Expecter) DeleteVariable(ctx any, name any, options ...any) *MockClient_DeleteVariable_Call {
	return &MockClient_DeleteVariable_Call{Call: _e.mock.On("DeleteVariable",
		append([]any{ctx, name}, options...)...)}
}

func (_c *MockClient_DeleteVariable_Call) Run(run func(ctx context.Context, name string, options ...client.DeleteVariableOption)) *MockClient_DeleteVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.DeleteVariableOption
		var variadicArgs []client.DeleteVariableOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.DeleteVariableOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_DeleteVariable_Call) Return(err error) *MockClient_DeleteVariable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteVariable_Call) RunAndReturn(run func(ctx context.Context, name string, options ...client.DeleteVariableOption) error) *MockClient_DeleteVariable_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVolume provides a mock function for the type MockClient
func (_mock *MockClient) DeleteVolume(ctx context.Context, name string, options ...client.DeleteVolumeOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, name, options)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.DeleteVolumeOption) error); ok {
		r0 = returnFunc(ctx, name, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVolume'
type MockClient_DeleteVolume_Call struct {
	*mock.Call
}

// DeleteVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options ...client.DeleteVolumeOption
func (_e *MockClient_Expecter) DeleteVolume(ctx any, name any, options ...any) *MockClient_DeleteVolume_Call {
	return &MockClient_DeleteVolume_Call{Call: _e.mock.On("DeleteVolume",
		append([]any{ctx, name}, options...)...)}
}

func (_c *MockClient_DeleteVolume_Call) Run(run func(ctx context.Context, name string, options ...client.DeleteVolumeOption)) *MockClient_DeleteVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.DeleteVolumeOption
		var variadicArgs []client.DeleteVolumeOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.DeleteVolumeOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_DeleteVolume_Call) Return(err error) *MockClient_DeleteVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteVolume_Call) RunAndReturn(run func(ctx context.Context, name string, options ...client.DeleteVolumeOption) error) *MockClient_DeleteVolume_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockClient
func (_mock *MockClient) Get(ctx context.Context, name string) (client.Workload, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 client.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Workload, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Workload); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(client.Workload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClient_Expecter) Get(ctx any, name any) *MockClient_Get_Call {
	return &MockClient_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockClient_Get_Call) Run(run func(ctx context.Context, name string)) *MockClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Get_Call) Return(workload client.Workload, err error) *MockClient_Get_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *MockClient_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (client.Workload, error)) *MockClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type MockClient
func (_mock *MockClient) GetSecret(ctx context.Context, name string) (client.Secret, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 client.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Secret, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Secret); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(client.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockClient_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClient_Expecter) GetSecret(ctx any, name any) *MockClient_GetSecret_Call {
	return &MockClient_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, name)}
}

func (_c *MockClient_GetSecret_Call) Run(run func(ctx context.Context, name string)) *MockClient_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetSecret_Call) Return(secret client.Secret, err error) *MockClient_GetSecret_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockClient_GetSecret_Call) RunAndReturn(run func(ctx context.Context, name string) (client.Secret, error)) *MockClient_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetService provides a mock function for the type MockClient
func (_mock *MockClient) GetService(ctx context.Context, name string) (client.Service, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetService")
	}

	var r0 client.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Service, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Service); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(client.Service)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetService'
type MockClient_GetService_Call struct {
	*mock.Call
}

// GetService is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClient_Expecter) GetService(ctx any, name any) *MockClient_GetService_Call {
	return &MockClient_GetService_Call{Call: _e.mock.On("GetService", ctx, name)}
}

func (_c *MockClient_GetService_Call) Run(run func(ctx context.Context, name string)) *MockClient_GetService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetService_Call) Return(service client.Service, err error) *MockClient_GetService_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockClient_GetService_Call) RunAndReturn(run func(ctx context.Context, name string) (client.Service, error)) *MockClient_GetService_Call {
	_c.Call.Return(run)
	return _c
}

// GetVariable provides a mock function for the type MockClient
func (_mock *MockClient) GetVariable(ctx context.Context, name string) (client.Variable, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetVariable")
	}

	var r0 client.Variable
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Variable, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Variable); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(client.Variable)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVariable'
type MockClient_GetVariable_Call struct {
	*mock.Call
}

// GetVariable is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClient_Expecter) GetVariable(ctx any, name any) *MockClient_GetVariable_Call {
	return &MockClient_GetVariable_Call{Call: _e.mock.On("GetVariable", ctx, name)}
}

func (_c *MockClient_GetVariable_Call) Run(run func(ctx context.Context, name string)) *MockClient_GetVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetVariable_Call) Return(variable client.Variable, err error) *MockClient_GetVariable_Call {
	_c.Call.Return(variable, err)
	return _c
}

func (_c *MockClient_GetVariable_Call) RunAndReturn(run func(ctx context.Context, name string) (client.Variable, error)) *MockClient_GetVariable_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolume provides a mock function for the type MockClient
func (_mock *MockClient) GetVolume(ctx context.Context, name string) (client.Volume, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetVolume")
	}

	var r0 client.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Volume, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Volume); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(client.Volume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolume'
type MockClient_GetVolume_Call struct {
	*mock.Call
}

// GetVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClient_Expecter) GetVolume(ctx any, name any) *MockClient_GetVolume_Call {
	return &MockClient_GetVolume_Call{Call: _e.mock.On("GetVolume", ctx, name)}
}

func (_c *MockClient_GetVolume_Call) Run(run func(ctx context.Context, name string)) *MockClient_GetVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetVolume_Call) Return(volume client.Volume, err error) *MockClient_GetVolume_Call {
	_c.Call.Return(volume, err)
	return _c
}

func (_c *MockClient_GetVolume_Call) RunAndReturn(run func(ctx context.Context, name string) (client.Volume, error)) *MockClient_GetVolume_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockClient
func (_mock *MockClient) List(ctx context.Context, queries ...string) ([]client.Workload, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []client.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]client.Workload, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []client.Workload); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockClient_Expecter) List(ctx any, queries ...any) *MockClient_List_Call {
	return &MockClient_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockClient_List_Call) Run(run func(ctx context.Context, queries ...string)) *MockClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClient_List_Call) Return(workloads []client.Workload, err error) *MockClient_List_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *MockClient_List_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]client.Workload, error)) *MockClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListServices provides a mock function for the type MockClient
func (_mock *MockClient) ListServices(ctx context.Context, queries ...string) ([]client.Service, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 []client.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]client.Service, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []client.Service); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServices'
type MockClient_ListServices_Call struct {
	*mock.Call
}

// ListServices is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockClient_Expecter) ListServices(ctx any, queries ...any) *MockClient_ListServices_Call {
	return &MockClient_ListServices_Call{Call: _e.mock.On("ListServices",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockClient_ListServices_Call) Run(run func(ctx context.Context, queries ...string)) *MockClient_ListServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClient_ListServices_Call) Return(services []client.Service, err error) *MockClient_ListServices_Call {
	_c.Call.Return(services, err)
	return _c
}

func (_c *MockClient_ListServices_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]client.Service, error)) *MockClient_ListServices_Call {
	_c.Call.Return(run)
	return _c
}

// ListVariables provides a mock function for the type MockClient
func (_mock *MockClient) ListVariables(ctx context.Context, queries ...string) ([]client.Variable, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListVariables")
	}

	var r0 []client.Variable
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]client.Variable, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []client.Variable); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Variable)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListVariables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVariables'
type MockClient_ListVariables_Call struct {
	*mock.Call
}

// ListVariables is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockClient_Expecter) ListVariables(ctx any, queries ...any) *MockClient_ListVariables_Call {
	return &MockClient_ListVariables_Call{Call: _e.mock.On("ListVariables",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockClient_ListVariables_Call) Run(run func(ctx context.Context, queries ...string)) *MockClient_ListVariables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClient_ListVariables_Call) Return(variables []client.Variable, err error) *MockClient_ListVariables_Call {
	_c.Call.Return(variables, err)
	return _c
}

func (_c *MockClient_ListVariables_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]client.Variable, error)) *MockClient_ListVariables_Call {
	_c.Call.Return(run)
	return _c
}

// ListVolumes provides a mock function for the type MockClient
func (_mock *MockClient) ListVolumes(ctx context.Context, queries ...string) ([]client.Volume, error) {
	var tmpRet mock.Arguments
	if len(queries) > 0 {
		tmpRet = _mock.Called(ctx, queries)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListVolumes")
	}

	var r0 []client.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]client.Volume, error)); ok {
		return returnFunc(ctx, queries...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []client.Volume); ok {
		r0 = returnFunc(ctx, queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, queries...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVolumes'
type MockClient_ListVolumes_Call struct {
	*mock.Call
}

// ListVolumes is a helper method to define mock.On call
//   - ctx context.Context
//   - queries ...string
func (_e *MockClient_Expecter) ListVolumes(ctx any, queries ...any) *MockClient_ListVolumes_Call {
	return &MockClient_ListVolumes_Call{Call: _e.mock.On("ListVolumes",
		append([]any{ctx}, queries...)...)}
}

func (_c *MockClient_ListVolumes_Call) Run(run func(ctx context.Context, queries ...string)) *MockClient_ListVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClient_ListVolumes_Call) Return(volumes []client.Volume, err error) *MockClient_ListVolumes_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *MockClient_ListVolumes_Call) RunAndReturn(run func(ctx context.Context, queries ...string) ([]client.Volume, error)) *MockClient_ListVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// SetVariable provides a mock function for the type MockClient
func (_mock *MockClient) SetVariable(ctx context.Context, variable manifest.Variable, options ...client.ApplyOption) (client.Variable, bool, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, variable, options)
	} else {
		tmpRet = _mock.Called(ctx, variable)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SetVariable")
	}

	var r0 client.Variable
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Variable, ...client.ApplyOption) (client.Variable, bool, error)); ok {
		return returnFunc(ctx, variable, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifest.Variable, ...client.ApplyOption) client.Variable); ok {
		r0 = returnFunc(ctx, variable, options...)
	} else {
		r0 = ret.Get(0).(client.Variable)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifest.Variable, ...client.ApplyOption) bool); ok {
		r1 = returnFunc(ctx, variable, options...)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, manifest.Variable, ...client.ApplyOption) error); ok {
		r2 = returnFunc(ctx, variable, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_SetVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVariable'
type MockClient_SetVariable_Call struct {
	*mock.Call
}

// SetVariable is a helper method to define mock.On call
//   - ctx context.Context
//   - variable manifest.Variable
//   - options ...client.ApplyOption
func (_e *MockClient_Expecter) SetVariable(ctx any, variable any, options ...any) *MockClient_SetVariable_Call {
	return &MockClient_SetVariable_Call{Call: _e.mock.On("SetVariable",
		append([]any{ctx, variable}, options...)...)}
}

func (_c *MockClient_SetVariable_Call) Run(run func(ctx context.Context, variable manifest.Variable, options ...client.ApplyOption)) *MockClient_SetVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifest.Variable
		if args[1] != nil {
			arg1 = args[1].(manifest.Variable)
		}
		var arg2 []client.ApplyOption
		var variadicArgs []client.ApplyOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.ApplyOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_SetVariable_Call) Return(variable1 client.Variable, b bool, err error) *MockClient_SetVariable_Call {
	_c.Call.Return(variable1, b, err)
	return _c
}

func (_c *MockClient_SetVariable_Call) RunAndReturn(run func(ctx context.Context, variable manifest.Variable, options ...client.ApplyOption) (client.Variable, bool, error)) *MockClient_SetVariable_Call {
	_c.Call.Return(run)
	return _c
}
