name: go

concurrency:
  group: ${{ github.workflow }}/${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'api/openapi.yaml'
      - 'api/oapi-codegen.yaml'
      - '.mockery.yml'
      - 'Makefile'
      - 'scripts/delegated.sh'
      - '.github/workflows/go.yml'
      - '.github/actions/setup-go/action.yml'
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'api/openapi.yaml'
      - 'api/oapi-codegen.yaml'
      - '.mockery.yml'
      - 'Makefile'
      - 'scripts/delegated.sh'
      - '.github/workflows/go.yml'
      - '.github/actions/setup-go/action.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Go
        uses: ./.github/actions/setup-go
        with:
          cache-name: go

      - name: Run linter
        run: go tool staticcheck ./...

      - name: Run generators
        run: |
          go generate ./...
          git add .
          git diff --staged --exit-code

      - name: Run tests
        run: make test

      - name: Save the Go caches
        if: always()
        uses: ./.github/actions/setup-go
        with:
          mode: save
          cache-name: go
